#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "shell.y".
#

require 'racc/parser.rb'


require_relative 'parser_support'

module Rush
  class Parser < Racc::Parser

module_eval(<<'...end shell.y/module_eval...', 'shell.y', 271)

include Rush::ParserSupport
...end shell.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    17,    35,    37,   139,   138,   137,    43,    44,    45,    39,
    40,    46,    47,    31,    55,    56,    54,    48,    25,    53,
    12,    27,    28,     3,   150,    29,   133,   142,    30,     3,
     3,   160,    26,   159,   150,    41,    42,    17,    35,    37,
  -105,    55,    56,    43,    44,    45,    39,    40,    46,    47,
    31,    55,    56,   145,    54,    25,   149,    53,    27,    28,
   107,   107,    29,   155,     3,    30,   149,    55,    56,    26,
     3,     5,    41,    42,    72,    74,    37,   160,    48,   166,
    43,    44,    45,    39,    40,    46,    47,    77,    49,    37,
   102,   139,   138,    43,    44,    45,    39,    40,    46,    47,
     3,   107,    57,    61,     3,     3,     3,     3,    68,    41,
    42,    69,     3,    80,    81,    83,    83,    83,    17,    35,
    37,    48,    41,    42,    43,    44,    45,    39,    40,    46,
    47,    31,    83,    83,    83,    83,    25,     3,    12,    27,
    28,     3,     3,    29,    57,    96,    30,    97,   100,   102,
    26,   102,     3,    41,    42,    17,    35,    37,   110,     3,
     3,    43,    44,    45,    39,    40,    46,    47,    31,   102,
   123,     3,   125,    25,     3,    12,    27,    28,     3,    48,
    29,   130,     3,    30,   102,    48,   151,    26,     3,     3,
    41,    42,    17,    35,    37,   102,   158,   150,    43,    44,
    45,    39,    40,    46,    47,    31,   162,     3,   165,     3,
    25,   168,    12,    27,    28,     3,     3,    29,     3,   175,
    30,     3,     3,    77,    26,    37,   nil,    41,    42,    43,
    44,    45,    39,    40,    46,    47,   113,   nil,    37,   nil,
   nil,   nil,    43,    44,    45,    39,    40,    46,    47,   nil,
   nil,   nil,   nil,   nil,   nil,    17,    35,    37,    41,    42,
   nil,    43,    44,    45,    39,    40,    46,    47,    31,   nil,
   nil,    41,    42,    25,   nil,    12,    27,    28,   nil,   nil,
    29,   nil,   nil,    30,   nil,   nil,   nil,    26,   nil,   nil,
    41,    42,    17,    35,    37,   nil,   nil,   nil,    43,    44,
    45,    39,    40,    46,    47,    31,   nil,   nil,   nil,   nil,
    25,   nil,    12,    27,    28,   nil,   nil,    29,   nil,   nil,
    30,   nil,   nil,   nil,    26,   nil,   nil,    41,    42,    17,
    35,    37,   nil,   nil,   nil,    43,    44,    45,    39,    40,
    46,    47,    31,   nil,    31,   nil,   nil,    25,   nil,    25,
    27,    28,    27,    28,    29,   nil,    29,    30,   nil,    30,
   113,    26,    37,    26,    41,    42,    43,    44,    45,    39,
    40,    46,    47,   nil,   nil,   nil,   nil,   nil,   nil,    17,
    35,    37,   nil,   nil,   nil,    43,    44,    45,    39,    40,
    46,    47,    31,   nil,   nil,    41,    42,    25,   nil,    12,
    27,    28,   nil,   nil,    29,   nil,   nil,    30,   nil,   nil,
   nil,    26,   nil,   nil,    41,    42,    17,    35,    37,   nil,
   nil,   nil,    43,    44,    45,    39,    40,    46,    47,    31,
   nil,   nil,   nil,   nil,    25,   nil,    12,    27,    28,   nil,
   nil,    29,   nil,   nil,    30,   nil,   169,   nil,    26,   nil,
   nil,    41,    42,    17,    35,    37,   nil,   nil,   nil,    43,
    44,    45,    39,    40,    46,    47,    31,   nil,   nil,   nil,
   nil,    25,   nil,    12,    27,    28,   nil,   nil,    29,   nil,
   nil,    30,   nil,   176,   nil,    26,    37,   nil,    41,    42,
    43,    44,    45,    39,    40,    46,    47,    37,   nil,   nil,
   nil,    43,    44,    45,    39,    40,    46,    47,    43,    44,
    45,    39,    40,    46,    47,   nil,   nil,   nil,   nil,    41,
    42,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    41,    42,   nil,   nil,   nil,   nil,   nil,    41,    42 ]

racc_action_check = [
     2,     2,     2,   126,   126,   126,     2,     2,     2,     2,
     2,     2,     2,     2,     9,     9,     8,   108,     2,     8,
     2,     2,     2,    99,   135,     2,   123,   132,     2,   123,
   132,   148,     2,   148,   143,     2,     2,    12,    12,    12,
   108,    91,    91,    12,    12,    12,    12,    12,    12,    12,
    12,    98,    98,   135,    99,    12,   135,    99,    12,    12,
   123,   132,    12,   143,     0,    12,   143,   128,   128,    12,
    67,     1,    12,    12,    32,    32,    32,   161,     4,   161,
    32,    32,    32,    32,    32,    32,    32,    33,     5,    33,
    67,   167,   167,    33,    33,    33,    33,    33,    33,    33,
     6,    67,    11,    17,    25,    26,    27,    28,    29,    32,
    32,    30,    31,    39,    40,    41,    42,    43,    51,    51,
    51,    51,    33,    33,    51,    51,    51,    51,    51,    51,
    51,    51,    44,    45,    46,    47,    51,    55,    51,    51,
    51,    56,    57,    51,    58,    61,    51,    62,    64,    65,
    51,    66,    69,    51,    51,    52,    52,    52,    70,    96,
   102,    52,    52,    52,    52,    52,    52,    52,    52,   105,
   106,   107,   109,    52,   110,    52,    52,    52,   119,   120,
    52,   121,   125,    52,   131,   134,   136,    52,   138,   139,
    52,    52,    63,    63,    63,   141,   144,   149,    63,    63,
    63,    63,    63,    63,    63,    63,   152,   159,   160,   162,
    63,   163,    63,    63,    63,   166,   168,    63,   169,   170,
    63,   175,   176,    71,    63,    71,   nil,    63,    63,    71,
    71,    71,    71,    71,    71,    71,    75,   nil,    75,   nil,
   nil,   nil,    75,    75,    75,    75,    75,    75,    75,   nil,
   nil,   nil,   nil,   nil,   nil,    92,    92,    92,    71,    71,
   nil,    92,    92,    92,    92,    92,    92,    92,    92,   nil,
   nil,    75,    75,    92,   nil,    92,    92,    92,   nil,   nil,
    92,   nil,   nil,    92,   nil,   nil,   nil,    92,   nil,   nil,
    92,    92,    93,    93,    93,   nil,   nil,   nil,    93,    93,
    93,    93,    93,    93,    93,    93,   nil,   nil,   nil,   nil,
    93,   nil,    93,    93,    93,   nil,   nil,    93,   nil,   nil,
    93,   nil,   nil,   nil,    93,   nil,   nil,    93,    93,    94,
    94,    94,   nil,   nil,   nil,    94,    94,    94,    94,    94,
    94,    94,    94,   nil,   117,   nil,   nil,    94,   nil,   117,
    94,    94,   117,   117,    94,   nil,   117,    94,   nil,   117,
   111,    94,   111,   117,    94,    94,   111,   111,   111,   111,
   111,   111,   111,   nil,   nil,   nil,   nil,   nil,   nil,   118,
   118,   118,   nil,   nil,   nil,   118,   118,   118,   118,   118,
   118,   118,   118,   nil,   nil,   111,   111,   118,   nil,   118,
   118,   118,   nil,   nil,   118,   nil,   nil,   118,   nil,   nil,
   nil,   118,   nil,   nil,   118,   118,   164,   164,   164,   nil,
   nil,   nil,   164,   164,   164,   164,   164,   164,   164,   164,
   nil,   nil,   nil,   nil,   164,   nil,   164,   164,   164,   nil,
   nil,   164,   nil,   nil,   164,   nil,   164,   nil,   164,   nil,
   nil,   164,   164,   171,   171,   171,   nil,   nil,   nil,   171,
   171,   171,   171,   171,   171,   171,   171,   nil,   nil,   nil,
   nil,   171,   nil,   171,   171,   171,   nil,   nil,   171,   nil,
   nil,   171,   nil,   171,   nil,   171,    15,   nil,   171,   171,
    15,    15,    15,    15,    15,    15,    15,    59,   nil,   nil,
   nil,    59,    59,    59,    59,    59,    59,    59,    37,    37,
    37,    37,    37,    37,    37,   nil,   nil,   nil,   nil,    15,
    15,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    59,    59,   nil,   nil,   nil,   nil,   nil,    37,    37 ]

racc_action_pointer = [
    59,    71,    -2,   nil,    73,    88,    95,   nil,   -20,     8,
   nil,    69,    35,   nil,   nil,   482,   nil,    69,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    99,   100,   101,   102,    79,
   109,   107,    72,    85,   nil,   nil,   nil,   500,   nil,   111,
   112,   113,   114,   115,   130,   131,   132,   133,   nil,   nil,
   nil,   116,   153,   nil,   nil,   132,   136,   137,   111,   493,
   nil,   110,   126,   190,   113,   124,   126,    65,   nil,   147,
   142,   221,   nil,   nil,   nil,   234,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    35,   253,   290,   327,   nil,   154,   nil,    45,    18,
   nil,   nil,   155,   nil,   nil,   144,   142,   166,    12,   144,
   169,   358,   nil,   nil,   nil,   nil,   nil,   329,   377,   173,
   174,   155,   nil,    24,   nil,   177,   -14,   nil,    61,   nil,
   nil,   159,    25,   nil,   180,    22,   167,   nil,   183,   184,
   nil,   170,   nil,    32,   165,   nil,   nil,   nil,    -2,   195,
   nil,   nil,   190,   nil,   nil,   nil,   nil,   nil,   nil,   202,
   206,    44,   204,   179,   414,   nil,   210,    74,   211,   213,
   187,   451,   nil,   nil,   nil,   216,   217,   nil,   nil ]

racc_action_default = [
  -106,  -107,    -1,  -103,  -105,  -107,  -106,    -3,    -6,    -8,
    -9,   -12,  -107,   -14,   -16,   -17,   -19,   -77,   -23,   -24,
   -25,   -26,   -27,   -28,   -29,  -106,  -106,  -106,  -106,  -107,
  -107,  -106,   -74,   -76,   -79,   -81,   -87,  -107,   -89,  -107,
  -107,  -107,  -107,  -107,  -107,  -107,  -107,  -107,  -104,   179,
    -2,  -105,    -5,  -101,  -102,  -106,  -106,  -106,   -13,   -18,
   -20,  -107,  -107,  -107,  -107,  -107,  -107,  -106,   -39,  -106,
  -107,   -73,   -78,   -80,   -82,   -75,   -83,   -85,   -88,   -90,
   -91,   -92,   -93,  -100,   -94,   -95,   -96,   -97,   -98,   -99,
    -4,    -7,  -107,  -107,  -107,   -21,  -106,   -30,   -69,   -66,
   -31,   -32,  -106,   -33,   -35,  -107,  -107,  -106,   -43,  -107,
  -106,   -72,   -84,   -86,   -10,   -11,   -15,  -107,   -67,  -106,
   -71,  -107,   -36,  -107,   -42,  -106,  -107,   -22,   -68,   -70,
   -34,  -107,  -107,   -40,   -43,  -107,  -107,   -62,  -106,  -106,
   -37,  -107,   -41,  -107,  -107,   -46,   -47,   -49,  -107,  -107,
   -59,   -61,  -107,   -65,   -38,   -44,   -48,   -50,   -45,  -106,
  -107,  -107,  -106,   -55,   -56,   -60,  -106,   -63,  -106,  -106,
   -57,   -58,   -64,   -51,   -52,  -106,  -106,   -53,   -54 ]

racc_goto_table = [
     2,    62,    64,    65,    66,    51,    50,    70,    60,    52,
     9,   101,   103,   104,   105,    75,     7,   136,     1,   146,
   147,   114,   115,     6,    58,    73,    76,   156,   157,    82,
    84,    85,    86,    87,    88,    89,   116,   127,    59,    67,
   132,   143,   144,   161,   118,    71,    78,    79,   nil,   nil,
   nil,   122,    95,   111,   nil,    92,    93,    94,   172,     9,
    91,   nil,   nil,   nil,    76,    90,   108,   106,   112,   109,
   131,   nil,   nil,   nil,   nil,   nil,   nil,   140,   121,   141,
   nil,   nil,   nil,   nil,   nil,   nil,   126,   154,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   117,   nil,   120,   nil,
   119,   nil,   nil,   nil,   112,   nil,   nil,   124,   nil,   nil,
   nil,   nil,   nil,   nil,   152,   153,   nil,   nil,   nil,   129,
   nil,   nil,   134,   nil,   nil,   135,   128,   nil,   nil,   nil,
   nil,   134,   nil,   nil,   nil,   163,   nil,   nil,   167,   nil,
   nil,   nil,   170,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   164,
   nil,   nil,   nil,   nil,   nil,   nil,   171,   nil,   173,   174,
   nil,   nil,   nil,   nil,   nil,   177,   178 ]

racc_goto_check = [
     2,    24,    24,    24,    24,     5,     2,    24,    16,     7,
     8,    25,    25,    25,    27,    39,     4,    34,     1,    31,
    32,     9,     9,     3,    10,    16,    16,    31,    32,    43,
    43,    43,    43,    43,    43,    43,    11,    13,    14,    26,
    28,    29,    30,    33,    36,    38,    41,    42,   nil,   nil,
   nil,    25,    16,    39,   nil,     2,     2,     2,    34,     8,
     8,   nil,   nil,   nil,    16,     4,     5,     2,    16,     2,
    27,   nil,   nil,   nil,   nil,   nil,   nil,    25,    24,    27,
   nil,   nil,   nil,   nil,   nil,   nil,    24,    25,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,     5,   nil,
     7,   nil,   nil,   nil,    16,   nil,   nil,     2,   nil,   nil,
   nil,   nil,   nil,   nil,    24,    24,   nil,   nil,   nil,     2,
   nil,   nil,     5,   nil,   nil,     2,     8,   nil,   nil,   nil,
   nil,     5,   nil,   nil,   nil,    24,   nil,   nil,    24,   nil,
   nil,   nil,    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,     2,     2,
   nil,   nil,   nil,   nil,   nil,     2,     2 ]

racc_goto_pointer = [
   nil,    18,     0,    21,    14,    -1,   nil,     1,     8,   -71,
    12,   -58,   nil,   -80,    23,   nil,    -7,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -24,   -54,    10,   -53,   -83,   -94,
   -93,  -116,  -115,  -106,  -109,   nil,   -55,   nil,    13,   -18,
   nil,     9,    10,   -12 ]

racc_goto_default = [
   nil,   nil,    63,   nil,   nil,     4,     8,   nil,    98,    10,
    11,    13,    14,    15,   nil,    16,    34,    18,    19,    20,
    21,    22,    23,    24,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   148,   nil,    99,   nil,    32,   nil,   nil,
    33,    36,    38,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 41, :_reduce_1,
  3, 41, :_reduce_2,
  1, 43, :_reduce_3,
  3, 43, :_reduce_4,
  2, 44, :_reduce_5,
  1, 44, :_reduce_6,
  3, 46, :_reduce_7,
  1, 46, :_reduce_8,
  1, 48, :_reduce_9,
  4, 48, :_reduce_10,
  4, 48, :_reduce_11,
  1, 49, :_reduce_12,
  2, 49, :_reduce_13,
  1, 50, :_reduce_14,
  4, 50, :_reduce_15,
  1, 51, :_reduce_16,
  1, 51, :_reduce_17,
  2, 51, :_reduce_18,
  1, 51, :_reduce_19,
  1, 54, :_reduce_20,
  2, 54, :_reduce_21,
  5, 55, :_reduce_22,
  1, 53, :_reduce_23,
  1, 53, :_reduce_24,
  1, 53, :_reduce_25,
  1, 53, :_reduce_26,
  1, 53, :_reduce_27,
  1, 53, :_reduce_28,
  1, 53, :_reduce_29,
  3, 57, :_reduce_30,
  3, 58, :_reduce_31,
  3, 60, :_reduce_32,
  3, 61, :_reduce_33,
  3, 65, :_reduce_34,
  3, 62, :_reduce_35,
  4, 62, :_reduce_36,
  6, 62, :_reduce_37,
  7, 62, :_reduce_38,
  1, 66, :_reduce_39,
  1, 68, :_reduce_40,
  2, 68, :_reduce_41,
  2, 67, :_reduce_none,
  1, 67, :_reduce_none,
  7, 63, :_reduce_44,
  7, 63, :_reduce_45,
  6, 63, :_reduce_46,
  1, 69, :_reduce_47,
  2, 69, :_reduce_48,
  1, 70, :_reduce_49,
  2, 70, :_reduce_50,
  5, 71, :_reduce_51,
  5, 71, :_reduce_52,
  6, 71, :_reduce_53,
  6, 71, :_reduce_54,
  3, 72, :_reduce_55,
  3, 72, :_reduce_56,
  4, 72, :_reduce_57,
  4, 72, :_reduce_58,
  1, 73, :_reduce_59,
  3, 73, :_reduce_60,
  6, 59, :_reduce_61,
  5, 59, :_reduce_62,
  4, 74, :_reduce_63,
  5, 74, :_reduce_64,
  2, 74, :_reduce_65,
  2, 64, :_reduce_66,
  3, 64, :_reduce_67,
  3, 75, :_reduce_68,
  1, 75, :_reduce_69,
  2, 76, :_reduce_70,
  1, 76, :_reduce_71,
  3, 52, :_reduce_72,
  2, 52, :_reduce_73,
  1, 52, :_reduce_74,
  2, 52, :_reduce_75,
  1, 52, :_reduce_76,
  1, 80, :_reduce_77,
  1, 78, :_reduce_78,
  1, 77, :_reduce_79,
  2, 77, :_reduce_80,
  1, 77, :_reduce_81,
  2, 77, :_reduce_82,
  1, 79, :_reduce_83,
  2, 79, :_reduce_84,
  1, 79, :_reduce_85,
  2, 79, :_reduce_86,
  1, 56, :_reduce_87,
  2, 56, :_reduce_88,
  1, 56, :_reduce_89,
  2, 56, :_reduce_90,
  2, 82, :_reduce_91,
  2, 82, :_reduce_92,
  2, 81, :_reduce_93,
  2, 81, :_reduce_94,
  2, 81, :_reduce_95,
  2, 81, :_reduce_96,
  2, 81, :_reduce_97,
  2, 81, :_reduce_98,
  2, 81, :_reduce_99,
  1, 83, :_reduce_100,
  1, 47, :_reduce_101,
  1, 47, :_reduce_102,
  1, 45, :_reduce_none,
  2, 45, :_reduce_none,
  1, 42, :_reduce_none,
  0, 42, :_reduce_none ]

racc_reduce_n = 107

racc_shift_n = 179

racc_token_table = {
  false => 0,
  :error => 1,
  :WORD => 2,
  :ASSIGNMENT_WORD => 3,
  :IO_NUMBER => 4,
  :NEWLINE => 5,
  :AND_IF => 6,
  :OR_IF => 7,
  :DGREAT => 8,
  :LESSGREAT => 9,
  :CLOBBER => 10,
  :DLESS => 11,
  :DLESSDASH => 12,
  :GREATAND => 13,
  :LESSAND => 14,
  :If => 15,
  :Then => 16,
  :Else => 17,
  :Elif => 18,
  :Fi => 19,
  :Lbrace => 20,
  :Rbrace => 21,
  :Bang => 22,
  :While => 23,
  :Until => 24,
  :Do => 25,
  :Done => 26,
  :For => 27,
  :In => 28,
  :NAME => 29,
  :Case => 30,
  :Esac => 31,
  :DSEMI => 32,
  "|" => 33,
  "(" => 34,
  ")" => 35,
  ";" => 36,
  "<" => 37,
  ">" => 38,
  "&" => 39 }

racc_nt_base = 40

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "WORD",
  "ASSIGNMENT_WORD",
  "IO_NUMBER",
  "NEWLINE",
  "AND_IF",
  "OR_IF",
  "DGREAT",
  "LESSGREAT",
  "CLOBBER",
  "DLESS",
  "DLESSDASH",
  "GREATAND",
  "LESSAND",
  "If",
  "Then",
  "Else",
  "Elif",
  "Fi",
  "Lbrace",
  "Rbrace",
  "Bang",
  "While",
  "Until",
  "Do",
  "Done",
  "For",
  "In",
  "NAME",
  "Case",
  "Esac",
  "DSEMI",
  "\"|\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\"<\"",
  "\">\"",
  "\"&\"",
  "$start",
  "program",
  "linebreak",
  "complete_commands",
  "complete_command",
  "newline_list",
  "list",
  "separator_op",
  "and_or",
  "pipeline",
  "pipe_sequence",
  "command",
  "simple_command",
  "compound_command",
  "redirect_list",
  "function_definition",
  "io_redirect",
  "brace_group",
  "subshell",
  "if_clause",
  "while_clause",
  "until_clause",
  "for_clause",
  "case_clause",
  "compound_list",
  "do_group",
  "name",
  "sequential_sep",
  "wordlist",
  "case_list",
  "case_list_ns",
  "case_item",
  "case_item_ns",
  "patterns",
  "else_part",
  "term",
  "separator",
  "cmd_prefix",
  "cmd_word",
  "cmd_suffix",
  "cmd_name",
  "io_file",
  "io_here",
  "filename" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'shell.y', 23)
  def _reduce_1(val, _values, result)
     result = make_list([])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 24)
  def _reduce_2(val, _values, result)
     result = make_list(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 28)
  def _reduce_3(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 29)
  def _reduce_4(val, _values, result)
     result = val[0] + val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 33)
  def _reduce_5(val, _values, result)
     result = terminate_list(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 34)
  def _reduce_6(val, _values, result)
     result = terminate_list(val[0], ';')
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 38)
  def _reduce_7(val, _values, result)
     result = append_and_or(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 39)
  def _reduce_8(val, _values, result)
     result = [pending_entry(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 43)
  def _reduce_9(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 44)
  def _reduce_10(val, _values, result)
     result = make_and_or(val[0], :and, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 45)
  def _reduce_11(val, _values, result)
     result = make_and_or(val[0], :or, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 49)
  def _reduce_12(val, _values, result)
     result = make_pipeline(val[0], false)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 50)
  def _reduce_13(val, _values, result)
     result = make_pipeline(val[1], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 54)
  def _reduce_14(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 55)
  def _reduce_15(val, _values, result)
     result = val[0] << val[3]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 59)
  def _reduce_16(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 60)
  def _reduce_17(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 61)
  def _reduce_18(val, _values, result)
     result = make_redirected(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 62)
  def _reduce_19(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 66)
  def _reduce_20(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 67)
  def _reduce_21(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 74)
  def _reduce_22(val, _values, result)
     result = make_function(val[0], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 78)
  def _reduce_23(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 79)
  def _reduce_24(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 80)
  def _reduce_25(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 81)
  def _reduce_26(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 82)
  def _reduce_27(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 83)
  def _reduce_28(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 84)
  def _reduce_29(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 88)
  def _reduce_30(val, _values, result)
     result = make_brace_group(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 92)
  def _reduce_31(val, _values, result)
     result = make_subshell(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 96)
  def _reduce_32(val, _values, result)
     result = make_while(val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 100)
  def _reduce_33(val, _values, result)
     result = make_until(val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 104)
  def _reduce_34(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 108)
  def _reduce_35(val, _values, result)
     result = make_for(val[1], nil, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 109)
  def _reduce_36(val, _values, result)
     result = make_for(val[1], nil, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 110)
  def _reduce_37(val, _values, result)
     result = make_for(val[1], [], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 111)
  def _reduce_38(val, _values, result)
     result = make_for(val[1], val[4], val[6])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 115)
  def _reduce_39(val, _values, result)
     result = val[0].literal_text
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 119)
  def _reduce_40(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 120)
  def _reduce_41(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'shell.y', 129)
  def _reduce_44(val, _values, result)
     result = make_case(val[1], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 130)
  def _reduce_45(val, _values, result)
     result = make_case(val[1], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 131)
  def _reduce_46(val, _values, result)
     result = make_case(val[1], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 135)
  def _reduce_47(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 136)
  def _reduce_48(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 141)
  def _reduce_49(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 142)
  def _reduce_50(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 146)
  def _reduce_51(val, _values, result)
     result = make_case_item(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 147)
  def _reduce_52(val, _values, result)
     result = make_case_item(val[0], make_list([]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 148)
  def _reduce_53(val, _values, result)
     result = make_case_item(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 149)
  def _reduce_54(val, _values, result)
     result = make_case_item(val[1], make_list([]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 153)
  def _reduce_55(val, _values, result)
     result = make_case_item(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 154)
  def _reduce_56(val, _values, result)
     result = make_case_item(val[0], make_list([]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 155)
  def _reduce_57(val, _values, result)
     result = make_case_item(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 156)
  def _reduce_58(val, _values, result)
     result = make_case_item(val[1], make_list([]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 160)
  def _reduce_59(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 161)
  def _reduce_60(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 165)
  def _reduce_61(val, _values, result)
     result = make_if(val[1], val[3], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 166)
  def _reduce_62(val, _values, result)
     result = make_if(val[1], val[3], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 170)
  def _reduce_63(val, _values, result)
     result = make_if(val[1], val[3], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 171)
  def _reduce_64(val, _values, result)
     result = make_if(val[1], val[3], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 172)
  def _reduce_65(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 176)
  def _reduce_66(val, _values, result)
     result = make_list(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 177)
  def _reduce_67(val, _values, result)
     result = make_list(terminate_list(val[1], val[2]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 181)
  def _reduce_68(val, _values, result)
     result = append_and_or(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 182)
  def _reduce_69(val, _values, result)
     result = [pending_entry(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 186)
  def _reduce_70(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 187)
  def _reduce_71(val, _values, result)
     result = ';'
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 191)
  def _reduce_72(val, _values, result)
     result = make_simple_command(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 192)
  def _reduce_73(val, _values, result)
     result = make_simple_command(val[0], val[1], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 193)
  def _reduce_74(val, _values, result)
     result = make_simple_command(val[0], nil, [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 194)
  def _reduce_75(val, _values, result)
     result = make_simple_command([], val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 195)
  def _reduce_76(val, _values, result)
     result = make_simple_command([], val[0], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 199)
  def _reduce_77(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 203)
  def _reduce_78(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 207)
  def _reduce_79(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 208)
  def _reduce_80(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 209)
  def _reduce_81(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 210)
  def _reduce_82(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 214)
  def _reduce_83(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 215)
  def _reduce_84(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 216)
  def _reduce_85(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 217)
  def _reduce_86(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 221)
  def _reduce_87(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 222)
  def _reduce_88(val, _values, result)
     result = with_io_number(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 223)
  def _reduce_89(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 224)
  def _reduce_90(val, _values, result)
     result = with_io_number(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 230)
  def _reduce_91(val, _values, result)
     result = make_heredoc(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 231)
  def _reduce_92(val, _values, result)
     result = make_heredoc(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 235)
  def _reduce_93(val, _values, result)
     result = make_redirect(:in, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 236)
  def _reduce_94(val, _values, result)
     result = make_redirect(:out, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 237)
  def _reduce_95(val, _values, result)
     result = make_redirect(:append, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 238)
  def _reduce_96(val, _values, result)
     result = make_redirect(:readwrite, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 239)
  def _reduce_97(val, _values, result)
     result = make_redirect(:clobber, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 240)
  def _reduce_98(val, _values, result)
     result = make_redirect(:dup_out, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 241)
  def _reduce_99(val, _values, result)
     result = make_redirect(:dup_in, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 245)
  def _reduce_100(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 249)
  def _reduce_101(val, _values, result)
     result = '&'
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 250)
  def _reduce_102(val, _values, result)
     result = ';'
    result
  end
.,.,

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

# reduce 106 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Rush
