#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "shell.y".
#

require 'racc/parser.rb'


require_relative 'parser_support'

module Rush
  class Parser < Racc::Parser

module_eval(<<'...end shell.y/module_eval...', 'shell.y', 225)

include Rush::ParserSupport
...end shell.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    30,    32,    34,    40,   125,     3,    37,    38,    39,    27,
   111,   125,     3,     3,    22,    46,    12,    23,    24,    45,
   120,    25,   -83,     3,    26,     5,    30,    32,    34,   122,
    35,    36,    37,    38,    39,    27,   130,    46,    87,     3,
    22,    45,    40,    23,    24,    47,    48,    25,    87,   133,
    26,   132,    60,    62,    34,    82,    35,    36,    37,    38,
    39,    65,    41,    34,    87,    47,    48,    37,    38,    39,
    47,    48,    30,    32,    34,    40,    47,    48,    37,    38,
    39,    27,    35,    36,   117,   116,    22,     3,    12,    23,
    24,    35,    36,    25,    49,     3,    26,     3,    30,    32,
    34,     3,    35,    36,    37,    38,    39,    27,   117,   116,
   115,    56,    22,    57,    12,    23,    24,     3,    68,    25,
    68,    68,    26,    68,    30,    32,    34,    68,    35,    36,
    37,    38,    39,    27,     3,    37,    38,    39,    22,     3,
    12,    23,    24,     3,    65,    25,    34,    49,    26,    78,
    37,    38,    39,    82,    35,    36,    93,    82,    34,    35,
    36,     3,    37,    38,    39,    93,    90,    34,     3,    82,
   102,    37,    38,    39,    35,    36,    30,    32,    34,     3,
   104,     3,    37,    38,    39,    27,    35,    36,     3,    40,
    22,   108,    12,    23,    24,    35,    36,    25,     3,    82,
    26,    40,    30,    32,    34,   126,    35,    36,    37,    38,
    39,    27,     3,     3,    82,   134,    22,     3,    12,    23,
    24,   137,     3,    25,   139,     3,    26,     3,    30,    32,
    34,   nil,    35,    36,    37,    38,    39,    27,   nil,   nil,
   nil,   nil,    22,   nil,   nil,    23,    24,   nil,   nil,    25,
   nil,   nil,    26,   nil,    30,    32,    34,   nil,    35,    36,
    37,    38,    39,    27,   nil,   nil,   nil,   nil,    22,   nil,
    12,    23,    24,   nil,   nil,    25,   nil,   nil,    26,   nil,
    30,    32,    34,   nil,    35,    36,    37,    38,    39,    27,
   nil,   nil,   nil,   nil,    22,   nil,    12,    23,    24,   nil,
   nil,    25,   nil,   nil,    26,   nil,   140,   nil,   nil,   nil,
    35,    36 ]

racc_action_check = [
     2,     2,     2,    88,   113,     0,     2,     2,     2,     2,
   102,   121,    80,   102,     2,     8,     2,     2,     2,     8,
   110,     2,    88,   110,     2,     1,    12,    12,    12,   113,
     2,     2,    12,    12,    12,    12,   121,    80,   102,    55,
    12,    80,     4,    12,    12,     9,     9,    12,   110,   124,
    12,   124,    28,    28,    28,    55,    12,    12,    28,    28,
    28,    29,     5,    29,    55,    74,    74,    29,    29,    29,
    79,    79,    43,    43,    43,    43,   106,   106,    43,    43,
    43,    43,    28,    28,   138,   138,    43,     6,    43,    43,
    43,    29,    29,    43,    11,    22,    43,    23,    44,    44,
    44,    24,    43,    43,    44,    44,    44,    44,   105,   105,
   105,    25,    44,    26,    44,    44,    44,    27,    35,    44,
    36,    37,    44,    38,    52,    52,    52,    39,    44,    44,
    52,    52,    52,    52,    47,    34,    34,    34,    52,    48,
    52,    52,    52,    49,    59,    52,    59,    50,    52,    51,
    59,    59,    59,    53,    52,    52,    63,    54,    63,    34,
    34,    57,    63,    63,    63,    91,    58,    91,    82,    85,
    86,    91,    91,    91,    59,    59,    75,    75,    75,    87,
    89,    90,    75,    75,    75,    75,    63,    63,    98,    99,
    75,   100,    75,    75,    75,    91,    91,    75,   104,   109,
    75,   112,    76,    76,    76,   114,    75,    75,    76,    76,
    76,    76,   116,   117,   119,   127,    76,   132,    76,    76,
    76,   133,   134,    76,   135,   139,    76,   140,    77,    77,
    77,   nil,    76,    76,    77,    77,    77,    77,   nil,   nil,
   nil,   nil,    77,   nil,   nil,    77,    77,   nil,   nil,    77,
   nil,   nil,    77,   nil,    97,    97,    97,   nil,    77,    77,
    97,    97,    97,    97,   nil,   nil,   nil,   nil,    97,   nil,
    97,    97,    97,   nil,   nil,    97,   nil,   nil,    97,   nil,
   136,   136,   136,   nil,    97,    97,   136,   136,   136,   136,
   nil,   nil,   nil,   nil,   136,   nil,   136,   136,   136,   nil,
   nil,   136,   nil,   nil,   136,   nil,   136,   nil,   nil,   nil,
   136,   136 ]

racc_action_pointer = [
     0,    25,    -2,   nil,    37,    62,    82,   nil,   -15,    39,
   nil,    65,    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    90,    92,    96,    86,   111,   112,    50,    59,
   nil,   nil,   nil,   nil,   127,   116,   118,   119,   121,   125,
   nil,   nil,   nil,    70,    96,   nil,   nil,   129,   134,   138,
   118,   132,   122,   132,   136,    34,   nil,   156,   154,   142,
   nil,   nil,   nil,   154,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    59,   174,   200,   226,   nil,    64,
     7,   nil,   163,   nil,   nil,   148,   146,   174,    -2,   156,
   176,   163,   nil,   nil,   nil,   nil,   nil,   252,   183,   184,
   169,   nil,     8,   nil,   193,    95,    70,   nil,   nil,   178,
    18,   nil,   196,     2,   190,   nil,   207,   208,   nil,   193,
   nil,     9,   nil,   nil,    20,   nil,   nil,   203,   nil,   nil,
   nil,   nil,   212,   219,   217,   196,   278,   nil,    71,   220,
   222,   nil,   nil,   nil ]

racc_action_default = [
   -84,   -85,    -1,   -81,   -83,   -85,   -84,    -3,    -6,    -8,
    -9,   -12,   -85,   -14,   -16,   -17,   -18,   -19,   -20,   -21,
   -22,   -23,   -84,   -84,   -84,   -85,   -85,   -84,   -58,   -60,
   -61,   -63,   -65,   -71,   -85,   -85,   -85,   -85,   -85,   -85,
   -82,   144,    -2,   -83,    -5,   -79,   -80,   -84,   -84,   -84,
   -13,   -85,   -85,   -85,   -85,   -84,   -32,   -84,   -85,   -57,
   -62,   -64,   -66,   -59,   -67,   -69,   -72,   -73,   -78,   -74,
   -75,   -76,   -77,    -4,    -7,   -85,   -85,   -85,   -24,   -53,
   -50,   -25,   -84,   -26,   -28,   -85,   -85,   -84,   -36,   -85,
   -84,   -56,   -68,   -70,   -10,   -11,   -15,   -51,   -84,   -55,
   -85,   -29,   -85,   -35,   -84,   -85,   -52,   -54,   -27,   -85,
   -85,   -33,   -36,   -85,   -85,   -46,   -84,   -84,   -30,   -85,
   -34,   -85,   -38,   -39,   -85,   -43,   -45,   -85,   -49,   -31,
   -37,   -40,   -84,   -85,   -84,   -85,   -85,   -44,   -47,   -84,
   -84,   -48,   -41,   -42 ]

racc_goto_table = [
     2,    44,    51,    53,    54,    43,    42,    58,    74,    81,
    83,    84,    85,   114,    63,   123,    79,     7,    94,    95,
     1,    61,    64,   131,    67,    69,    70,    71,    72,     6,
    50,    96,    55,   110,   121,    97,    59,    66,   nil,   nil,
   nil,   101,   nil,   nil,    91,   nil,   141,    75,    76,    77,
   nil,   nil,    64,   nil,    88,    86,    92,    89,    73,   109,
   nil,   106,   100,   nil,   nil,   118,   nil,   119,   nil,   nil,
   105,   nil,   nil,    98,   nil,   129,   nil,   nil,   nil,    99,
   nil,   nil,   nil,   nil,    92,   nil,   nil,   103,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   127,   128,   107,   nil,
    79,   112,   nil,   nil,   113,   nil,   nil,   nil,   nil,   112,
   nil,   nil,   135,   nil,   138,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   136,   nil,   nil,   nil,   nil,   nil,   nil,   142,
   143 ]

racc_goto_check = [
     2,     7,    20,    20,    20,     5,     2,    20,     8,    21,
    21,    21,    23,    28,    33,    26,     8,     4,     9,     9,
     1,    35,    35,    26,    37,    37,    37,    37,    37,     3,
    10,    11,    22,    24,    25,    30,    32,    36,   nil,   nil,
   nil,    21,   nil,   nil,    33,   nil,    28,     2,     2,     2,
   nil,   nil,    35,   nil,     5,     2,    35,     2,     4,    23,
   nil,     8,    20,   nil,   nil,    21,   nil,    23,   nil,   nil,
    20,   nil,   nil,     7,   nil,    21,   nil,   nil,   nil,     5,
   nil,   nil,   nil,   nil,    35,   nil,   nil,     2,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    20,    20,     2,   nil,
     8,     5,   nil,   nil,     2,   nil,   nil,   nil,   nil,     5,
   nil,   nil,    20,   nil,    20,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,     2,
     2 ]

racc_goto_pointer = [
   nil,    20,     0,    27,    15,    -1,   nil,    -7,   -36,   -57,
    18,   -46,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   -20,   -44,     7,   -43,   -69,   -79,   -98,   nil,   -92,   nil,
   -45,   nil,     8,   -15,   nil,    -7,     3,   -11 ]

racc_goto_default = [
   nil,   nil,    52,   nil,   nil,     4,     8,   nil,     9,    10,
    11,    13,    14,    15,    16,    17,    18,    19,    20,    21,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   124,   nil,    80,
   nil,    28,   nil,   nil,    29,    31,    33,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 36, :_reduce_1,
  3, 36, :_reduce_2,
  1, 38, :_reduce_3,
  3, 38, :_reduce_4,
  2, 39, :_reduce_5,
  1, 39, :_reduce_6,
  3, 41, :_reduce_7,
  1, 41, :_reduce_8,
  1, 43, :_reduce_9,
  4, 43, :_reduce_10,
  4, 43, :_reduce_11,
  1, 44, :_reduce_12,
  2, 44, :_reduce_13,
  1, 45, :_reduce_14,
  4, 45, :_reduce_15,
  1, 46, :_reduce_16,
  1, 46, :_reduce_17,
  1, 48, :_reduce_18,
  1, 48, :_reduce_19,
  1, 48, :_reduce_20,
  1, 48, :_reduce_21,
  1, 48, :_reduce_22,
  1, 48, :_reduce_23,
  3, 49, :_reduce_24,
  3, 51, :_reduce_25,
  3, 52, :_reduce_26,
  3, 56, :_reduce_27,
  3, 53, :_reduce_28,
  4, 53, :_reduce_29,
  6, 53, :_reduce_30,
  7, 53, :_reduce_31,
  1, 57, :_reduce_32,
  1, 59, :_reduce_33,
  2, 59, :_reduce_34,
  2, 58, :_reduce_none,
  1, 58, :_reduce_none,
  7, 54, :_reduce_37,
  6, 54, :_reduce_38,
  1, 60, :_reduce_39,
  2, 60, :_reduce_40,
  5, 61, :_reduce_41,
  5, 61, :_reduce_42,
  1, 62, :_reduce_43,
  3, 62, :_reduce_44,
  6, 50, :_reduce_45,
  5, 50, :_reduce_46,
  4, 63, :_reduce_47,
  5, 63, :_reduce_48,
  2, 63, :_reduce_49,
  2, 55, :_reduce_50,
  3, 55, :_reduce_51,
  3, 64, :_reduce_52,
  1, 64, :_reduce_53,
  2, 65, :_reduce_54,
  1, 65, :_reduce_55,
  3, 47, :_reduce_56,
  2, 47, :_reduce_57,
  1, 47, :_reduce_58,
  2, 47, :_reduce_59,
  1, 47, :_reduce_60,
  1, 69, :_reduce_61,
  1, 67, :_reduce_62,
  1, 66, :_reduce_63,
  2, 66, :_reduce_64,
  1, 66, :_reduce_65,
  2, 66, :_reduce_66,
  1, 68, :_reduce_67,
  2, 68, :_reduce_68,
  1, 68, :_reduce_69,
  2, 68, :_reduce_70,
  1, 70, :_reduce_71,
  2, 70, :_reduce_72,
  2, 71, :_reduce_73,
  2, 71, :_reduce_74,
  2, 71, :_reduce_75,
  2, 71, :_reduce_76,
  2, 71, :_reduce_77,
  1, 72, :_reduce_78,
  1, 42, :_reduce_79,
  1, 42, :_reduce_80,
  1, 40, :_reduce_none,
  2, 40, :_reduce_none,
  1, 37, :_reduce_none,
  0, 37, :_reduce_none ]

racc_reduce_n = 85

racc_shift_n = 144

racc_token_table = {
  false => 0,
  :error => 1,
  :WORD => 2,
  :ASSIGNMENT_WORD => 3,
  :IO_NUMBER => 4,
  :NEWLINE => 5,
  :AND_IF => 6,
  :OR_IF => 7,
  :DGREAT => 8,
  :LESSGREAT => 9,
  :CLOBBER => 10,
  :If => 11,
  :Then => 12,
  :Else => 13,
  :Elif => 14,
  :Fi => 15,
  :Lbrace => 16,
  :Rbrace => 17,
  :Bang => 18,
  :While => 19,
  :Until => 20,
  :Do => 21,
  :Done => 22,
  :For => 23,
  :In => 24,
  :NAME => 25,
  :Case => 26,
  :Esac => 27,
  :DSEMI => 28,
  "|" => 29,
  ";" => 30,
  ")" => 31,
  "<" => 32,
  ">" => 33,
  "&" => 34 }

racc_nt_base = 35

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "WORD",
  "ASSIGNMENT_WORD",
  "IO_NUMBER",
  "NEWLINE",
  "AND_IF",
  "OR_IF",
  "DGREAT",
  "LESSGREAT",
  "CLOBBER",
  "If",
  "Then",
  "Else",
  "Elif",
  "Fi",
  "Lbrace",
  "Rbrace",
  "Bang",
  "While",
  "Until",
  "Do",
  "Done",
  "For",
  "In",
  "NAME",
  "Case",
  "Esac",
  "DSEMI",
  "\"|\"",
  "\";\"",
  "\")\"",
  "\"<\"",
  "\">\"",
  "\"&\"",
  "$start",
  "program",
  "linebreak",
  "complete_commands",
  "complete_command",
  "newline_list",
  "list",
  "separator_op",
  "and_or",
  "pipeline",
  "pipe_sequence",
  "command",
  "simple_command",
  "compound_command",
  "brace_group",
  "if_clause",
  "while_clause",
  "until_clause",
  "for_clause",
  "case_clause",
  "compound_list",
  "do_group",
  "name",
  "sequential_sep",
  "wordlist",
  "case_list",
  "case_item",
  "patterns",
  "else_part",
  "term",
  "separator",
  "cmd_prefix",
  "cmd_word",
  "cmd_suffix",
  "cmd_name",
  "io_redirect",
  "io_file",
  "filename" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'shell.y', 23)
  def _reduce_1(val, _values, result)
     result = make_list([])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 24)
  def _reduce_2(val, _values, result)
     result = make_list(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 28)
  def _reduce_3(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 29)
  def _reduce_4(val, _values, result)
     result = val[0] + val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 33)
  def _reduce_5(val, _values, result)
     result = terminate_list(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 34)
  def _reduce_6(val, _values, result)
     result = terminate_list(val[0], ';')
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 38)
  def _reduce_7(val, _values, result)
     result = append_and_or(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 39)
  def _reduce_8(val, _values, result)
     result = [pending_entry(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 43)
  def _reduce_9(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 44)
  def _reduce_10(val, _values, result)
     result = make_and_or(val[0], :and, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 45)
  def _reduce_11(val, _values, result)
     result = make_and_or(val[0], :or, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 49)
  def _reduce_12(val, _values, result)
     result = make_pipeline(val[0], false)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 50)
  def _reduce_13(val, _values, result)
     result = make_pipeline(val[1], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 54)
  def _reduce_14(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 55)
  def _reduce_15(val, _values, result)
     result = val[0] << val[3]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 59)
  def _reduce_16(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 60)
  def _reduce_17(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 64)
  def _reduce_18(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 65)
  def _reduce_19(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 66)
  def _reduce_20(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 67)
  def _reduce_21(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 68)
  def _reduce_22(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 69)
  def _reduce_23(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 73)
  def _reduce_24(val, _values, result)
     result = make_brace_group(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 77)
  def _reduce_25(val, _values, result)
     result = make_while(val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 81)
  def _reduce_26(val, _values, result)
     result = make_until(val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 85)
  def _reduce_27(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 89)
  def _reduce_28(val, _values, result)
     result = make_for(val[1], nil, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 90)
  def _reduce_29(val, _values, result)
     result = make_for(val[1], nil, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 91)
  def _reduce_30(val, _values, result)
     result = make_for(val[1], [], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 92)
  def _reduce_31(val, _values, result)
     result = make_for(val[1], val[4], val[6])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 96)
  def _reduce_32(val, _values, result)
     result = val[0].literal_text
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 100)
  def _reduce_33(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 101)
  def _reduce_34(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

# reduce 35 omitted

# reduce 36 omitted

module_eval(<<'.,.,', 'shell.y', 110)
  def _reduce_37(val, _values, result)
     result = make_case(val[1], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 111)
  def _reduce_38(val, _values, result)
     result = make_case(val[1], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 115)
  def _reduce_39(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 116)
  def _reduce_40(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 120)
  def _reduce_41(val, _values, result)
     result = make_case_item(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 121)
  def _reduce_42(val, _values, result)
     result = make_case_item(val[0], make_list([]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 125)
  def _reduce_43(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 126)
  def _reduce_44(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 130)
  def _reduce_45(val, _values, result)
     result = make_if(val[1], val[3], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 131)
  def _reduce_46(val, _values, result)
     result = make_if(val[1], val[3], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 135)
  def _reduce_47(val, _values, result)
     result = make_if(val[1], val[3], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 136)
  def _reduce_48(val, _values, result)
     result = make_if(val[1], val[3], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 137)
  def _reduce_49(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 141)
  def _reduce_50(val, _values, result)
     result = make_list(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 142)
  def _reduce_51(val, _values, result)
     result = make_list(terminate_list(val[1], val[2]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 146)
  def _reduce_52(val, _values, result)
     result = append_and_or(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 147)
  def _reduce_53(val, _values, result)
     result = [pending_entry(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 151)
  def _reduce_54(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 152)
  def _reduce_55(val, _values, result)
     result = ';'
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 156)
  def _reduce_56(val, _values, result)
     result = make_simple_command(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 157)
  def _reduce_57(val, _values, result)
     result = make_simple_command(val[0], val[1], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 158)
  def _reduce_58(val, _values, result)
     result = make_simple_command(val[0], nil, [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 159)
  def _reduce_59(val, _values, result)
     result = make_simple_command([], val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 160)
  def _reduce_60(val, _values, result)
     result = make_simple_command([], val[0], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 164)
  def _reduce_61(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 168)
  def _reduce_62(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 172)
  def _reduce_63(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 173)
  def _reduce_64(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 174)
  def _reduce_65(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 175)
  def _reduce_66(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 179)
  def _reduce_67(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 180)
  def _reduce_68(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 181)
  def _reduce_69(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 182)
  def _reduce_70(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 186)
  def _reduce_71(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 187)
  def _reduce_72(val, _values, result)
     result = with_io_number(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 191)
  def _reduce_73(val, _values, result)
     result = make_redirect(:in, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 192)
  def _reduce_74(val, _values, result)
     result = make_redirect(:out, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 193)
  def _reduce_75(val, _values, result)
     result = make_redirect(:append, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 194)
  def _reduce_76(val, _values, result)
     result = make_redirect(:readwrite, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 195)
  def _reduce_77(val, _values, result)
     result = make_redirect(:clobber, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 199)
  def _reduce_78(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 203)
  def _reduce_79(val, _values, result)
     result = '&'
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 204)
  def _reduce_80(val, _values, result)
     result = ';'
    result
  end
.,.,

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Rush
