#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "shell.y".
#

require 'racc/parser.rb'


require_relative 'parser_support'

module Rush
  class Parser < Racc::Parser

module_eval(<<'...end shell.y/module_eval...', 'shell.y', 255)

include Rush::ParserSupport
...end shell.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    17,    35,    37,    55,    56,   147,    43,    44,    45,    39,
    40,    46,    47,    31,    55,    56,    54,    48,    25,    53,
    12,    27,    28,     3,     3,    29,   133,   142,    30,     3,
     3,     5,    26,     3,   144,    41,    42,    17,    35,    37,
   -96,   147,    48,    43,    44,    45,    39,    40,    46,    47,
    31,    55,    56,   102,    54,    25,    49,    53,    27,    28,
   107,   107,    29,     3,   107,    30,   139,   138,   137,    26,
   152,    57,    41,    42,    72,    74,    37,   155,    61,   154,
    43,    44,    45,    39,    40,    46,    47,    77,     3,    37,
    55,    56,     3,    43,    44,    45,    39,    40,    46,    47,
   139,   138,     3,     3,    68,    69,     3,    80,    81,    41,
    42,    83,    83,    83,    83,    83,    83,    83,    17,    35,
    37,    48,    41,    42,    43,    44,    45,    39,    40,    46,
    47,    31,     3,     3,     3,    57,    25,    96,    12,    27,
    28,    97,   100,    29,   102,   102,    30,     3,   110,     3,
    26,     3,   102,    41,    42,    17,    35,    37,   123,     3,
   125,    43,    44,    45,    39,    40,    46,    47,    31,     3,
     3,    48,   130,    25,     3,    12,    27,    28,   102,    48,
    29,   148,     3,    30,     3,   102,   156,    26,     3,   159,
    41,    42,    17,    35,    37,     3,   161,     3,    43,    44,
    45,    39,    40,    46,    47,    31,     3,   nil,   nil,   nil,
    25,   nil,    12,    27,    28,   nil,   nil,    29,   nil,   nil,
    30,   nil,   nil,    77,    26,    37,   nil,    41,    42,    43,
    44,    45,    39,    40,    46,    47,   113,   nil,    37,   nil,
   nil,   nil,    43,    44,    45,    39,    40,    46,    47,   nil,
   nil,   nil,   nil,   nil,   nil,    17,    35,    37,    41,    42,
   nil,    43,    44,    45,    39,    40,    46,    47,    31,   nil,
   nil,    41,    42,    25,   nil,    12,    27,    28,   nil,   nil,
    29,   nil,   nil,    30,   nil,   nil,   nil,    26,   nil,   nil,
    41,    42,    17,    35,    37,   nil,   nil,   nil,    43,    44,
    45,    39,    40,    46,    47,    31,   nil,   nil,   nil,   nil,
    25,   nil,    12,    27,    28,   nil,   nil,    29,   nil,   nil,
    30,   nil,   nil,   nil,    26,   nil,   nil,    41,    42,    17,
    35,    37,   nil,   nil,   nil,    43,    44,    45,    39,    40,
    46,    47,    31,   nil,    31,   nil,   nil,    25,   nil,    25,
    27,    28,    27,    28,    29,   nil,    29,    30,   nil,    30,
   113,    26,    37,    26,    41,    42,    43,    44,    45,    39,
    40,    46,    47,   nil,   nil,   nil,   nil,   nil,   nil,    17,
    35,    37,   nil,   nil,   nil,    43,    44,    45,    39,    40,
    46,    47,    31,   nil,   nil,    41,    42,    25,   nil,    12,
    27,    28,   nil,   nil,    29,   nil,   nil,    30,   nil,   nil,
   nil,    26,   nil,   nil,    41,    42,    17,    35,    37,   nil,
   nil,   nil,    43,    44,    45,    39,    40,    46,    47,    31,
   nil,   nil,   nil,   nil,    25,   nil,    12,    27,    28,   nil,
   nil,    29,   nil,   nil,    30,   nil,   162,   nil,    26,    37,
   nil,    41,    42,    43,    44,    45,    39,    40,    46,    47,
    37,   nil,   nil,   nil,    43,    44,    45,    39,    40,    46,
    47,    43,    44,    45,    39,    40,    46,    47,   nil,   nil,
   nil,   nil,    41,    42,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    41,    42,   nil,   nil,   nil,   nil,   nil,
    41,    42 ]

racc_action_check = [
     2,     2,     2,     9,     9,   135,     2,     2,     2,     2,
     2,     2,     2,     2,    91,    91,     8,   108,     2,     8,
     2,     2,     2,    99,     0,     2,   123,   132,     2,   123,
   132,     1,     2,    67,   135,     2,     2,    12,    12,    12,
   108,   143,     4,    12,    12,    12,    12,    12,    12,    12,
    12,    98,    98,    67,    99,    12,     5,    99,    12,    12,
   123,   132,    12,     6,    67,    12,   126,   126,   126,    12,
   143,    11,    12,    12,    32,    32,    32,   146,    17,   146,
    32,    32,    32,    32,    32,    32,    32,    33,    25,    33,
   128,   128,    26,    33,    33,    33,    33,    33,    33,    33,
   160,   160,    27,    28,    29,    30,    31,    39,    40,    32,
    32,    41,    42,    43,    44,    45,    46,    47,    51,    51,
    51,    51,    33,    33,    51,    51,    51,    51,    51,    51,
    51,    51,    55,    56,    57,    58,    51,    61,    51,    51,
    51,    62,    64,    51,    65,    66,    51,    69,    70,    96,
    51,   102,   105,    51,    51,    52,    52,    52,   106,   107,
   109,    52,    52,    52,    52,    52,    52,    52,    52,   110,
   119,   120,   121,    52,   125,    52,    52,    52,   131,   134,
    52,   136,   138,    52,   139,   141,   149,    52,   154,   155,
    52,    52,    63,    63,    63,   156,   157,   161,    63,    63,
    63,    63,    63,    63,    63,    63,   162,   nil,   nil,   nil,
    63,   nil,    63,    63,    63,   nil,   nil,    63,   nil,   nil,
    63,   nil,   nil,    71,    63,    71,   nil,    63,    63,    71,
    71,    71,    71,    71,    71,    71,    75,   nil,    75,   nil,
   nil,   nil,    75,    75,    75,    75,    75,    75,    75,   nil,
   nil,   nil,   nil,   nil,   nil,    92,    92,    92,    71,    71,
   nil,    92,    92,    92,    92,    92,    92,    92,    92,   nil,
   nil,    75,    75,    92,   nil,    92,    92,    92,   nil,   nil,
    92,   nil,   nil,    92,   nil,   nil,   nil,    92,   nil,   nil,
    92,    92,    93,    93,    93,   nil,   nil,   nil,    93,    93,
    93,    93,    93,    93,    93,    93,   nil,   nil,   nil,   nil,
    93,   nil,    93,    93,    93,   nil,   nil,    93,   nil,   nil,
    93,   nil,   nil,   nil,    93,   nil,   nil,    93,    93,    94,
    94,    94,   nil,   nil,   nil,    94,    94,    94,    94,    94,
    94,    94,    94,   nil,   117,   nil,   nil,    94,   nil,   117,
    94,    94,   117,   117,    94,   nil,   117,    94,   nil,   117,
   111,    94,   111,   117,    94,    94,   111,   111,   111,   111,
   111,   111,   111,   nil,   nil,   nil,   nil,   nil,   nil,   118,
   118,   118,   nil,   nil,   nil,   118,   118,   118,   118,   118,
   118,   118,   118,   nil,   nil,   111,   111,   118,   nil,   118,
   118,   118,   nil,   nil,   118,   nil,   nil,   118,   nil,   nil,
   nil,   118,   nil,   nil,   118,   118,   158,   158,   158,   nil,
   nil,   nil,   158,   158,   158,   158,   158,   158,   158,   158,
   nil,   nil,   nil,   nil,   158,   nil,   158,   158,   158,   nil,
   nil,   158,   nil,   nil,   158,   nil,   158,   nil,   158,    15,
   nil,   158,   158,    15,    15,    15,    15,    15,    15,    15,
    59,   nil,   nil,   nil,    59,    59,    59,    59,    59,    59,
    59,    37,    37,    37,    37,    37,    37,    37,   nil,   nil,
   nil,   nil,    15,    15,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    59,    59,   nil,   nil,   nil,   nil,   nil,
    37,    37 ]

racc_action_pointer = [
    19,    31,    -2,   nil,    37,    56,    58,   nil,   -20,    -3,
   nil,    38,    35,   nil,   nil,   445,   nil,    44,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    83,    87,    97,    98,    75,
   103,   101,    72,    85,   nil,   nil,   nil,   463,   nil,   105,
   106,   109,   110,   111,   112,   113,   114,   115,   nil,   nil,
   nil,   116,   153,   nil,   nil,   127,   128,   129,   102,   456,
   nil,   102,   120,   190,   107,   119,   120,    28,   nil,   142,
   132,   221,   nil,   nil,   nil,   234,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     8,   253,   290,   327,   nil,   144,   nil,    45,    18,
   nil,   nil,   146,   nil,   nil,   127,   130,   154,    12,   132,
   164,   358,   nil,   nil,   nil,   nil,   nil,   329,   377,   165,
   166,   146,   nil,    24,   nil,   169,    49,   nil,    84,   nil,
   nil,   153,    25,   nil,   174,     3,   162,   nil,   177,   179,
   nil,   160,   nil,    39,   nil,   nil,    44,   nil,   nil,   170,
   nil,   nil,   nil,   nil,   183,   187,   190,   164,   414,   nil,
    83,   192,   201,   nil,   nil,   nil ]

racc_action_default = [
   -97,   -98,    -1,   -94,   -96,   -98,   -97,    -3,    -6,    -8,
    -9,   -12,   -98,   -14,   -16,   -17,   -19,   -68,   -23,   -24,
   -25,   -26,   -27,   -28,   -29,   -97,   -97,   -97,   -97,   -98,
   -98,   -97,   -65,   -67,   -70,   -72,   -78,   -98,   -80,   -98,
   -98,   -98,   -98,   -98,   -98,   -98,   -98,   -98,   -95,   166,
    -2,   -96,    -5,   -92,   -93,   -97,   -97,   -97,   -13,   -18,
   -20,   -98,   -98,   -98,   -98,   -98,   -98,   -97,   -39,   -97,
   -98,   -64,   -69,   -71,   -73,   -66,   -74,   -76,   -79,   -81,
   -82,   -83,   -84,   -91,   -85,   -86,   -87,   -88,   -89,   -90,
    -4,    -7,   -98,   -98,   -98,   -21,   -97,   -30,   -60,   -57,
   -31,   -32,   -97,   -33,   -35,   -98,   -98,   -97,   -43,   -98,
   -97,   -63,   -75,   -77,   -10,   -11,   -15,   -98,   -58,   -97,
   -62,   -98,   -36,   -98,   -42,   -97,   -98,   -22,   -59,   -61,
   -34,   -98,   -98,   -40,   -43,   -98,   -98,   -53,   -97,   -97,
   -37,   -98,   -41,   -98,   -45,   -46,   -98,   -50,   -52,   -98,
   -56,   -38,   -44,   -47,   -97,   -98,   -97,   -98,   -98,   -51,
   -54,   -97,   -97,   -55,   -48,   -49 ]

racc_goto_table = [
     2,    62,    64,    65,    66,    51,    50,    70,    60,    52,
    91,   101,   103,   104,   105,    75,     7,   114,   115,   145,
   136,    98,     1,     6,    58,    73,    76,   153,    82,    84,
    85,    86,    87,    88,    89,   116,   127,    59,    67,   132,
   143,   118,    71,    78,    79,   nil,   nil,   nil,   nil,   nil,
   nil,   122,    95,   111,   163,    92,    93,    94,   nil,   nil,
   nil,   nil,   nil,   nil,    76,    90,   108,   106,   112,   109,
   131,   nil,   nil,   nil,   nil,   nil,   128,   140,   121,   141,
   nil,   nil,   nil,   nil,   nil,   nil,   126,   151,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   117,   nil,   120,   nil,
   119,   nil,   nil,   nil,   112,   nil,   nil,   124,   nil,   nil,
   nil,   nil,   nil,   nil,   149,   150,    98,   nil,   nil,   129,
   nil,   nil,   134,   nil,   nil,   135,   nil,   nil,   nil,   nil,
   157,   134,   160,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   158,   nil,   nil,   nil,   nil,   nil,
   nil,   164,   165 ]

racc_goto_check = [
     2,    24,    24,    24,    24,     5,     2,    24,    16,     7,
     8,    25,    25,    25,    27,    37,     4,     9,     9,    30,
    32,     8,     1,     3,    10,    16,    16,    30,    41,    41,
    41,    41,    41,    41,    41,    11,    13,    14,    26,    28,
    29,    34,    36,    39,    40,   nil,   nil,   nil,   nil,   nil,
   nil,    25,    16,    37,    32,     2,     2,     2,   nil,   nil,
   nil,   nil,   nil,   nil,    16,     4,     5,     2,    16,     2,
    27,   nil,   nil,   nil,   nil,   nil,     8,    25,    24,    27,
   nil,   nil,   nil,   nil,   nil,   nil,    24,    25,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,     5,   nil,
     7,   nil,   nil,   nil,    16,   nil,   nil,     2,   nil,   nil,
   nil,   nil,   nil,   nil,    24,    24,     8,   nil,   nil,     2,
   nil,   nil,     5,   nil,   nil,     2,   nil,   nil,   nil,   nil,
    24,     5,    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,
   nil,     2,     2 ]

racc_goto_pointer = [
   nil,    22,     0,    21,    14,    -1,   nil,     1,   -42,   -75,
    12,   -59,   nil,   -81,    22,   nil,    -7,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -24,   -54,     9,   -53,   -84,   -95,
  -116,   nil,  -106,   nil,   -58,   nil,    10,   -18,   nil,     6,
     7,   -13 ]

racc_goto_default = [
   nil,   nil,    63,   nil,   nil,     4,     8,   nil,     9,    10,
    11,    13,    14,    15,   nil,    16,    34,    18,    19,    20,
    21,    22,    23,    24,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   146,   nil,    99,   nil,    32,   nil,   nil,    33,    36,
    38,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 41, :_reduce_1,
  3, 41, :_reduce_2,
  1, 43, :_reduce_3,
  3, 43, :_reduce_4,
  2, 44, :_reduce_5,
  1, 44, :_reduce_6,
  3, 46, :_reduce_7,
  1, 46, :_reduce_8,
  1, 48, :_reduce_9,
  4, 48, :_reduce_10,
  4, 48, :_reduce_11,
  1, 49, :_reduce_12,
  2, 49, :_reduce_13,
  1, 50, :_reduce_14,
  4, 50, :_reduce_15,
  1, 51, :_reduce_16,
  1, 51, :_reduce_17,
  2, 51, :_reduce_18,
  1, 51, :_reduce_19,
  1, 54, :_reduce_20,
  2, 54, :_reduce_21,
  5, 55, :_reduce_22,
  1, 53, :_reduce_23,
  1, 53, :_reduce_24,
  1, 53, :_reduce_25,
  1, 53, :_reduce_26,
  1, 53, :_reduce_27,
  1, 53, :_reduce_28,
  1, 53, :_reduce_29,
  3, 57, :_reduce_30,
  3, 58, :_reduce_31,
  3, 60, :_reduce_32,
  3, 61, :_reduce_33,
  3, 65, :_reduce_34,
  3, 62, :_reduce_35,
  4, 62, :_reduce_36,
  6, 62, :_reduce_37,
  7, 62, :_reduce_38,
  1, 66, :_reduce_39,
  1, 68, :_reduce_40,
  2, 68, :_reduce_41,
  2, 67, :_reduce_none,
  1, 67, :_reduce_none,
  7, 63, :_reduce_44,
  6, 63, :_reduce_45,
  1, 69, :_reduce_46,
  2, 69, :_reduce_47,
  5, 70, :_reduce_48,
  5, 70, :_reduce_49,
  1, 71, :_reduce_50,
  3, 71, :_reduce_51,
  6, 59, :_reduce_52,
  5, 59, :_reduce_53,
  4, 72, :_reduce_54,
  5, 72, :_reduce_55,
  2, 72, :_reduce_56,
  2, 64, :_reduce_57,
  3, 64, :_reduce_58,
  3, 73, :_reduce_59,
  1, 73, :_reduce_60,
  2, 74, :_reduce_61,
  1, 74, :_reduce_62,
  3, 52, :_reduce_63,
  2, 52, :_reduce_64,
  1, 52, :_reduce_65,
  2, 52, :_reduce_66,
  1, 52, :_reduce_67,
  1, 78, :_reduce_68,
  1, 76, :_reduce_69,
  1, 75, :_reduce_70,
  2, 75, :_reduce_71,
  1, 75, :_reduce_72,
  2, 75, :_reduce_73,
  1, 77, :_reduce_74,
  2, 77, :_reduce_75,
  1, 77, :_reduce_76,
  2, 77, :_reduce_77,
  1, 56, :_reduce_78,
  2, 56, :_reduce_79,
  1, 56, :_reduce_80,
  2, 56, :_reduce_81,
  2, 80, :_reduce_82,
  2, 80, :_reduce_83,
  2, 79, :_reduce_84,
  2, 79, :_reduce_85,
  2, 79, :_reduce_86,
  2, 79, :_reduce_87,
  2, 79, :_reduce_88,
  2, 79, :_reduce_89,
  2, 79, :_reduce_90,
  1, 81, :_reduce_91,
  1, 47, :_reduce_92,
  1, 47, :_reduce_93,
  1, 45, :_reduce_none,
  2, 45, :_reduce_none,
  1, 42, :_reduce_none,
  0, 42, :_reduce_none ]

racc_reduce_n = 98

racc_shift_n = 166

racc_token_table = {
  false => 0,
  :error => 1,
  :WORD => 2,
  :ASSIGNMENT_WORD => 3,
  :IO_NUMBER => 4,
  :NEWLINE => 5,
  :AND_IF => 6,
  :OR_IF => 7,
  :DGREAT => 8,
  :LESSGREAT => 9,
  :CLOBBER => 10,
  :DLESS => 11,
  :DLESSDASH => 12,
  :GREATAND => 13,
  :LESSAND => 14,
  :If => 15,
  :Then => 16,
  :Else => 17,
  :Elif => 18,
  :Fi => 19,
  :Lbrace => 20,
  :Rbrace => 21,
  :Bang => 22,
  :While => 23,
  :Until => 24,
  :Do => 25,
  :Done => 26,
  :For => 27,
  :In => 28,
  :NAME => 29,
  :Case => 30,
  :Esac => 31,
  :DSEMI => 32,
  "|" => 33,
  "(" => 34,
  ")" => 35,
  ";" => 36,
  "<" => 37,
  ">" => 38,
  "&" => 39 }

racc_nt_base = 40

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "WORD",
  "ASSIGNMENT_WORD",
  "IO_NUMBER",
  "NEWLINE",
  "AND_IF",
  "OR_IF",
  "DGREAT",
  "LESSGREAT",
  "CLOBBER",
  "DLESS",
  "DLESSDASH",
  "GREATAND",
  "LESSAND",
  "If",
  "Then",
  "Else",
  "Elif",
  "Fi",
  "Lbrace",
  "Rbrace",
  "Bang",
  "While",
  "Until",
  "Do",
  "Done",
  "For",
  "In",
  "NAME",
  "Case",
  "Esac",
  "DSEMI",
  "\"|\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\"<\"",
  "\">\"",
  "\"&\"",
  "$start",
  "program",
  "linebreak",
  "complete_commands",
  "complete_command",
  "newline_list",
  "list",
  "separator_op",
  "and_or",
  "pipeline",
  "pipe_sequence",
  "command",
  "simple_command",
  "compound_command",
  "redirect_list",
  "function_definition",
  "io_redirect",
  "brace_group",
  "subshell",
  "if_clause",
  "while_clause",
  "until_clause",
  "for_clause",
  "case_clause",
  "compound_list",
  "do_group",
  "name",
  "sequential_sep",
  "wordlist",
  "case_list",
  "case_item",
  "patterns",
  "else_part",
  "term",
  "separator",
  "cmd_prefix",
  "cmd_word",
  "cmd_suffix",
  "cmd_name",
  "io_file",
  "io_here",
  "filename" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'shell.y', 23)
  def _reduce_1(val, _values, result)
     result = make_list([])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 24)
  def _reduce_2(val, _values, result)
     result = make_list(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 28)
  def _reduce_3(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 29)
  def _reduce_4(val, _values, result)
     result = val[0] + val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 33)
  def _reduce_5(val, _values, result)
     result = terminate_list(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 34)
  def _reduce_6(val, _values, result)
     result = terminate_list(val[0], ';')
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 38)
  def _reduce_7(val, _values, result)
     result = append_and_or(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 39)
  def _reduce_8(val, _values, result)
     result = [pending_entry(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 43)
  def _reduce_9(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 44)
  def _reduce_10(val, _values, result)
     result = make_and_or(val[0], :and, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 45)
  def _reduce_11(val, _values, result)
     result = make_and_or(val[0], :or, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 49)
  def _reduce_12(val, _values, result)
     result = make_pipeline(val[0], false)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 50)
  def _reduce_13(val, _values, result)
     result = make_pipeline(val[1], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 54)
  def _reduce_14(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 55)
  def _reduce_15(val, _values, result)
     result = val[0] << val[3]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 59)
  def _reduce_16(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 60)
  def _reduce_17(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 61)
  def _reduce_18(val, _values, result)
     result = make_redirected(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 62)
  def _reduce_19(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 66)
  def _reduce_20(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 67)
  def _reduce_21(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 74)
  def _reduce_22(val, _values, result)
     result = make_function(val[0], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 78)
  def _reduce_23(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 79)
  def _reduce_24(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 80)
  def _reduce_25(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 81)
  def _reduce_26(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 82)
  def _reduce_27(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 83)
  def _reduce_28(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 84)
  def _reduce_29(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 88)
  def _reduce_30(val, _values, result)
     result = make_brace_group(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 92)
  def _reduce_31(val, _values, result)
     result = make_subshell(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 96)
  def _reduce_32(val, _values, result)
     result = make_while(val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 100)
  def _reduce_33(val, _values, result)
     result = make_until(val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 104)
  def _reduce_34(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 108)
  def _reduce_35(val, _values, result)
     result = make_for(val[1], nil, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 109)
  def _reduce_36(val, _values, result)
     result = make_for(val[1], nil, val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 110)
  def _reduce_37(val, _values, result)
     result = make_for(val[1], [], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 111)
  def _reduce_38(val, _values, result)
     result = make_for(val[1], val[4], val[6])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 115)
  def _reduce_39(val, _values, result)
     result = val[0].literal_text
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 119)
  def _reduce_40(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 120)
  def _reduce_41(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'shell.y', 129)
  def _reduce_44(val, _values, result)
     result = make_case(val[1], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 130)
  def _reduce_45(val, _values, result)
     result = make_case(val[1], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 134)
  def _reduce_46(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 135)
  def _reduce_47(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 139)
  def _reduce_48(val, _values, result)
     result = make_case_item(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 140)
  def _reduce_49(val, _values, result)
     result = make_case_item(val[0], make_list([]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 144)
  def _reduce_50(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 145)
  def _reduce_51(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 149)
  def _reduce_52(val, _values, result)
     result = make_if(val[1], val[3], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 150)
  def _reduce_53(val, _values, result)
     result = make_if(val[1], val[3], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 154)
  def _reduce_54(val, _values, result)
     result = make_if(val[1], val[3], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 155)
  def _reduce_55(val, _values, result)
     result = make_if(val[1], val[3], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 156)
  def _reduce_56(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 160)
  def _reduce_57(val, _values, result)
     result = make_list(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 161)
  def _reduce_58(val, _values, result)
     result = make_list(terminate_list(val[1], val[2]))
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 165)
  def _reduce_59(val, _values, result)
     result = append_and_or(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 166)
  def _reduce_60(val, _values, result)
     result = [pending_entry(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 170)
  def _reduce_61(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 171)
  def _reduce_62(val, _values, result)
     result = ';'
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 175)
  def _reduce_63(val, _values, result)
     result = make_simple_command(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 176)
  def _reduce_64(val, _values, result)
     result = make_simple_command(val[0], val[1], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 177)
  def _reduce_65(val, _values, result)
     result = make_simple_command(val[0], nil, [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 178)
  def _reduce_66(val, _values, result)
     result = make_simple_command([], val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 179)
  def _reduce_67(val, _values, result)
     result = make_simple_command([], val[0], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 183)
  def _reduce_68(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 187)
  def _reduce_69(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 191)
  def _reduce_70(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 192)
  def _reduce_71(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 193)
  def _reduce_72(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 194)
  def _reduce_73(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 198)
  def _reduce_74(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 199)
  def _reduce_75(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 200)
  def _reduce_76(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 201)
  def _reduce_77(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 205)
  def _reduce_78(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 206)
  def _reduce_79(val, _values, result)
     result = with_io_number(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 207)
  def _reduce_80(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 208)
  def _reduce_81(val, _values, result)
     result = with_io_number(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 214)
  def _reduce_82(val, _values, result)
     result = make_heredoc(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 215)
  def _reduce_83(val, _values, result)
     result = make_heredoc(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 219)
  def _reduce_84(val, _values, result)
     result = make_redirect(:in, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 220)
  def _reduce_85(val, _values, result)
     result = make_redirect(:out, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 221)
  def _reduce_86(val, _values, result)
     result = make_redirect(:append, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 222)
  def _reduce_87(val, _values, result)
     result = make_redirect(:readwrite, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 223)
  def _reduce_88(val, _values, result)
     result = make_redirect(:clobber, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 224)
  def _reduce_89(val, _values, result)
     result = make_redirect(:dup_out, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 225)
  def _reduce_90(val, _values, result)
     result = make_redirect(:dup_in, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 229)
  def _reduce_91(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 233)
  def _reduce_92(val, _values, result)
     result = '&'
    result
  end
.,.,

module_eval(<<'.,.,', 'shell.y', 234)
  def _reduce_93(val, _values, result)
     result = ';'
    result
  end
.,.,

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

# reduce 97 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Rush
