# frozen_string_literal: true

SimpleCov.start do
  enable_coverage :branch
  track_files 'lib/**/*.rb'
  add_filter '/spec/'
  add_filter 'rush/parser.rb' # generated by racc; excluded from coverage

  # Guardrail, not dogma: rush aims for 100% meaningful coverage, but shell
  # behaviour crosses fork/exec boundaries that SimpleCov cannot observe.
  minimum_coverage line: 95, branch: 90
end
