# frozen_string_literal: true

SimpleCov.start do
  enable_coverage :branch
  track_files 'lib/**/*.rb'
  add_filter '/spec/'
  add_filter '/benchmark/' # opt-in measurement tooling, not shipped production code
  add_filter 'rush/parser.rb' # generated by racc; excluded from coverage

  # parallel_tests gives every shard a distinct command name. SimpleCov locks and
  # merges their result sets; only the final shard waits for the others, renders
  # the combined report, and applies these thresholds. Earlier shards use the
  # no-output formatter so they do not overwrite coverage/ with partial reports.
  group = ENV.fetch('TEST_ENV_NUMBER', nil)
  groups = ENV.fetch('PARALLEL_TEST_GROUPS', nil)
  if group && group != groups
    formatter SimpleCov::Formatter::SimpleFormatter
  else
    # coverage/coverage.json is what CI ships to Codecov; the JSON formatter is
    # simplecov's own runtime dependency, so no extra Gemfile entry.
    require 'simplecov_json_formatter'
    formatter SimpleCov::Formatter::MultiFormatter.new(
      [SimpleCov::Formatter::HTMLFormatter, SimpleCov::Formatter::JSONFormatter]
    )
  end

  # Guardrail, not dogma: rush aims for 100% meaningful coverage, but shell
  # behaviour crosses fork/exec boundaries that SimpleCov cannot observe.
  minimum_coverage line: 95, branch: 90
end
