# frozen_string_literal: true

SimpleCov.start do
  enable_coverage :branch
  track_files 'lib/**/*.rb'
  add_filter '/spec/'
  add_filter 'rush/parser.rb' # generated by racc; excluded from coverage
  # Coverage is a regression signal, not an architecture constraint: the floor
  # leaves headroom for irreducible OS-boundary code (fork children, real-fd
  # dup/close) that only manifests in a real subprocess, so designs are chosen on
  # merit and verified against dash differentially rather than contorted to be
  # in-process testable. Keep in-process logic well covered; don't chase the tail.
  minimum_coverage line: 95, branch: 90
end
