# typed: true

# Hand-written shim: lib/rush/parser.rb is generated by Racc and excluded from the
# Sorbet check (sorbet/config), mirroring the Steep sig/rush/parser.rbs stub. This
# lets the rest of lib resolve Rush::Parser's public surface (constructor + #parse).
module Rush
  class Parser
    def initialize(lexer); end
    def parse; end
  end
end
