# typed: true
# frozen_string_literal: true

# Hand-written shim: lib/rush/parser.rb is generated by Racc and excluded from the
# Sorbet check (sorbet/config), mirroring the Steep sig/rush/parser.rbs stub. The
# public start-symbol result is precise; only Racc's internal semantic stack stays
# untyped behind ParserSupport#do_parse.
module Rush
  # Public surface of the generated Racc parser.
  class Parser
    extend T::Sig

    sig { params(lexer: Lexer).void }
    def initialize(lexer); end

    sig { returns(AST::List) }
    def parse; end
  end

  # Methods supplied to the checked mixin by its generated Racc::Parser host.
  module ParserSupport
    extend T::Sig

    private

    sig { returns(T.untyped) }
    def do_parse; end

    sig { params(token_id: Integer).returns(String) }
    def token_to_str(token_id); end
  end
end
