module Rush
  module AST
    # `until cond; do body; done` — runs the body until the condition succeeds.
    class Until < Node
      extend T::Sig

      @condition: Node

      @body: Node

      attr_reader condition: Node

      attr_reader body: Node

      def initialize: (Node condition, Node body) -> void

      def execute: (Executor executor) -> Status
    end
  end
end
