module Rush
  module AST
    # `until cond; do body; done` — runs the body until the condition succeeds.
    class Until < ConditionLoop
      extend T::Sig

      private

      def kind: () -> :until
    end
  end
end
