module Rush
  module AST
    # `until cond; do body; done` — runs the body until the condition succeeds.
    class Until < Node
      @condition: untyped

      @body: untyped

      attr_reader condition: untyped

      attr_reader body: untyped

      def initialize: (untyped condition, untyped body) -> void

      def execute: (untyped executor) -> untyped
    end
  end
end
