module Rush
  module AST
    # `while cond; do body; done` — runs the body while the condition succeeds.
    class While < Node
      @condition: Node

      @body: Node

      attr_reader condition: Node

      attr_reader body: Node

      def initialize: (Node condition, Node body) -> void

      def execute: (Executor executor) -> Status
    end
  end
end
