# frozen_string_literal: true

require_relative 'rush/version'
require_relative 'rush/errors'
require_relative 'rush/status'
require_relative 'rush/system_calls'
require_relative 'rush/environment'
require_relative 'rush/function_table'
require_relative 'rush/shell_state'
require_relative 'rush/io_table'
require_relative 'rush/here_doc'

require_relative 'rush/ast/node'
require_relative 'rush/ast/word_segment'
require_relative 'rush/ast/word'
require_relative 'rush/ast/param_ref'
require_relative 'rush/ast/assignment'
require_relative 'rush/ast/redirect'
require_relative 'rush/ast/simple_command'
require_relative 'rush/ast/pipeline'
require_relative 'rush/ast/and_or'
require_relative 'rush/ast/list'
require_relative 'rush/ast/brace_group'
require_relative 'rush/ast/subshell'
require_relative 'rush/ast/if_node'
require_relative 'rush/ast/while_node'
require_relative 'rush/ast/until_node'
require_relative 'rush/ast/for_node'
require_relative 'rush/ast/case_node'
require_relative 'rush/ast/function_def'

require_relative 'rush/redirection/file_redirect'
require_relative 'rush/redirection/here_doc_redirect'
require_relative 'rush/redirection/registry'

require_relative 'rush/expansion/resolver'
require_relative 'rush/expansion/parameter_forms'
require_relative 'rush/expansion/pattern_removal'
require_relative 'rush/expansion/parameter_expander'
require_relative 'rush/expansion/command_substitution'
require_relative 'rush/expansion/ifs_scanner'
require_relative 'rush/expansion/field_splitter'
require_relative 'rush/expansion/read_splitter'
require_relative 'rush/expansion/pipeline'

require_relative 'rush/builtins/base'
require_relative 'rush/builtins/registry'
require_relative 'rush/builtins/colon'
require_relative 'rush/builtins/true_'
require_relative 'rush/builtins/false_'
require_relative 'rush/builtins/echo'
require_relative 'rush/builtins/exit'
require_relative 'rush/builtins/pwd'
require_relative 'rush/builtins/cd'
require_relative 'rush/builtins/break_'
require_relative 'rush/builtins/continue_'
require_relative 'rush/builtins/return_'
require_relative 'rush/builtins/test_expr'
require_relative 'rush/builtins/test_'
require_relative 'rush/builtins/set'
require_relative 'rush/builtins/shift'
require_relative 'rush/builtins/export'
require_relative 'rush/builtins/readonly'
require_relative 'rush/builtins/unset'
require_relative 'rush/builtins/eval'
require_relative 'rush/builtins/read'
require_relative 'rush/builtins/printf_formatter'
require_relative 'rush/builtins/printf'
require_relative 'rush/builtins/dot'
require_relative 'rush/builtins/exec'
require_relative 'rush/builtins/defaults'

require_relative 'rush/external'
require_relative 'rush/command_runner'
require_relative 'rush/pipeline_runner'
require_relative 'rush/subshell_runner'
require_relative 'rush/loop_control_handling'
require_relative 'rush/loop_runner'
require_relative 'rush/for_runner'
require_relative 'rush/function_runner'
require_relative 'rush/executor'

require_relative 'rush/lexer'
require_relative 'rush/parser_support'
require_relative 'rush/parser'
require_relative 'rush/repl'
require_relative 'rush/cli'
