# frozen_string_literal: true

# Core language, expansion, builtins, options, functions, and shell-parameter cases.
module DifferentialLanguageCorpus
  CASES = [
    '[ -n x ] && echo y',
    '[ -z "" ] && echo y',
    '[ -z nonempty ]; echo $?',
    'test abc = abc && echo eq',
    'test abc = abd || echo ne',
    '[ 3 -lt 10 ] && echo lt',
    '[ 10 -ge 10 ] && echo ge',
    '[ 10 -ne 10 ]; echo $?',
    'if [ ! -n "" ]; then echo blank; fi',
    'test ! abc = abc; echo $?',
    '[ "(" = "(" ] && echo paren',
    '[ \( -n x \) ] && echo group',
    '[ \( a = a \) ] && echo y',
    '[ \( a = b \) ]; echo $?',
    '[ \( \( -n x \) \) ] && echo nested',
    '[ ! \( a = b \) ] && echo neg',
    '[ \( \) ]; echo $?',
    'test \( \( \( a \) \) \); echo $?',
    '[ a = b = c ]; echo $?',
    '[ x = ]; echo $?',
    '[ a = a -a b = b ] && echo both',
    '[ a = a -a b = c ]; echo $?',
    '[ a = b -o b = b ] && echo either',
    '[ a = b -o b = c ]; echo $?',
    '[ 1 -eq 1 -a 2 -lt 3 -a x = x ] && echo chain',
    '[ x -o y -a "" ] && echo and-binds-tighter',
    '[ "" -a y -o z ] && echo or-arm',
    '[ ! x -o y ]; echo $?',
    '[ ! "" -a y ] && echo peeled',
    '[ ! x -a ! y ]; echo $?',
    '[ ! "" -o ! "" ] && echo bangs',
    '[ x -a ! "" ] && echo inner-bang',
    '[ \( x -o "" \) -a y ] && echo grouped',
    '[ \( x -a "" \) -o \( y \) ] && echo group-or',
    '[ ! \( x -o y \) ]; echo $?',
    '[ x -a ]; echo $?',
    '[ x -o ] && echo lone-or',
    '[ x -o y -eq 3 ] 2>/dev/null; echo $?',
    '[ = -a = ] && echo op-words',
    '[ -e -a -e ] 2>/dev/null; echo $?',
    '[ -n -a ] && echo unary-op-word',
    '[ -z -a ]; echo $?',
    '[ ! = ! ] && echo bang-eq',
    'x=5; [ "$x" -eq 5 ] && echo five',
    'test; echo $?',
    'test a b c; echo $?',
    '[ -d / ] && echo y',
    '[ -e /dev/null ] && echo y',
    '[ -f /dev/null ]; echo $?',
    '[ -r /dev/null ] && echo y',
    '[ -s /dev/null ]; echo $?',
    '[ -f /no/such/rush_xyz ]; echo $?',
    '[ -p /dev/null ]; echo $?',
    '[ -c /dev/null ] && echo chardev',
    '[ -b /dev/null ]; echo $?',
    '[ -S /dev/null ]; echo $?',
    '[ -g /dev/null ]; echo $?',
    '[ -u /dev/null ]; echo $?',
    'd=$(mktemp -d); mkfifo "$d/p"; [ -p "$d/p" ]; echo $?; rm -rf "$d"',
    'd=$(mktemp -d); touch "$d/f"; chmod 2755 "$d/f"; [ -g "$d/f" ] && [ ! -u "$d/f" ] && echo sgid; rm -rf "$d"',
    'd=$(mktemp -d); touch "$d/f"; chmod 4755 "$d/f"; [ -u "$d/f" ] && [ ! -g "$d/f" ] && echo suid; rm -rf "$d"',
    '[ -t 0 ]; echo $?',
    '[ -t 1 ]; echo $?',
    '[ -t 27 ]; echo $?',
    '[ -t -3 ]; echo $?',
    '[ -t 99999999999999999999 ]; echo $?',
    '[ -t x ] 2>/dev/null; echo $?',
    '[ -t ] && echo bare-t',
    '[ -t = -t ] && echo operand-t',
    'cd /nonexistent-rush-xyz 2>/dev/null; echo [$?]',
    'kill -TERM $$; echo alive',
    'kill -INT $$; echo alive',
    "echo a \\\nb",
    "true && \\\necho hi",
    "ec\\\nho joined",
    "echo \"a\\\nb\"",
    "echo 'a\\\nb'",
    "X=a\\\nb\necho $X",
    "read v <<EOF\na\\\nb\nEOF\necho [$v]",
    "read v <<'EOF'\na\\\nb\nEOF\necho [$v]",
    "read v <<'EOF'\na\\ b c\nEOF\nprintf '%s\\n' \"$v\"",
    "read -r v <<'EOF'\na\\ b\nEOF\nprintf '%s\\n' \"$v\"",
    "echo one # trail \\\necho two",
    'echo a \\',
    "true &\\\n& echo hi",
    "echo one |\\\n| echo two",
    "false &\\\n& echo no; echo [$?]",
    "echo hi 2\\\n>/dev/null",
    "echo dup >\\\n&1",
    "cat <\\\n<EOF\nsplit\nEOF",
    "cat <<\\\n-EOF\n\ttabbed\n\tEOF",
    "case x in x) echo a ;\\\n; y) echo b; esac",
    "true &\\\n\\\n& echo doubled",
    'case x in x) echo hi; esac',
    'case x in a) ;; *) echo b; esac',
    'case x in a) esac; echo [$?]',
    'case x in (x) echo paren;; esac',
    'case ":a:" in (*":a:"*) echo m;; (*) echo n;; esac',
    'case a in b) echo no;; a) case i in (i) echo inner; esac; echo outer; esac',
    'case a in [[:alpha:]]) echo alpha;; *) echo no;; esac',
    'case 7 in [![:digit:]]) echo no;; [[:digit:]]) echo digit;; esac',
    'case _ in [a[:digit:]_]) echo mixed;; esac',
    'case ] in [a\]b[:digit:]]) echo escaped;; esac',
    'case 5 in "[[:digit:]]") echo wrong;; *) echo quoted;; esac',
    'echo esac',
    'echo [$-]',
    'set -e; echo [$-]',
    'set -aCefuvx; echo [$-]',
    'set -o pipefail; echo [$-]',
    'set -eu; echo [$-]; set +e; echo [$-]',
    'set a b c; echo "$1 $2 $3 $#"',
    'set a b c; shift; echo "$1 $#"',
    'set a b c; shift 2; echo "$1 $#"',
    'set -- x y; echo "$# $1 $2"',
    'set --; echo "[$#]"',
    'set a b c; shift 0; echo $#',
    'p=$PPID; (test "$PPID" = "$p" && echo ppid-same)',
    "echo line=$LINENO\necho line=$LINENO",
    "if true; then\n echo line=$LINENO\nfi\necho after=$LINENO",
    "LINENO=abc; echo line=$LINENO\necho line=$LINENO",
    'unset LINENO; echo line=${LINENO-unset}',
    "eval 'echo eval=$LINENO\necho eval=$LINENO'",
    'set a b c; for x in "$@"; do echo "[$x]"; done',
    'set "a b" c; for x in "$@"; do echo "[$x]"; done',
    'set --; for x in "$@"; do echo no; done; echo done',
    'set -- -ab; getopts ab o; echo "$o:$OPTIND:$OPTARG:$?"; ' \
    'getopts ab o; echo "$o:$OPTIND:$OPTARG:$?"; getopts ab o; echo "$o:$OPTIND:$?"',
    'set -- -b val; getopts ab: o; echo "$o:$OPTIND:$OPTARG:$?"',
    'set -- -bval; getopts ab: o; echo "$o:$OPTIND:$OPTARG:$?"',
    'set -- -x; getopts a o 2>/dev/null; echo "$o:$OPTIND:${OPTARG-unset}:$?"',
    'set -- -a; getopts :a: o; echo "$o:$OPTIND:$OPTARG:$?"',
    'getopts a o -a; echo "$o:$OPTIND:$OPTARG:$?"',
    'set a b c; for x in $@; do echo "[$x]"; done',
    'set a b c; echo "$*"',
    'set a b c; echo "pre$@post"',
    'set one; echo "x$@y"',
    'set --; echo "z$@w"',
    'export X=hi; printenv X',
    'X=local; printenv X; echo "rc=$?"',
    'export X=hi; unset X; printenv X; echo "rc=$?"',
    'no-such-cmd-rush-xyz 2>&-; echo "rc=$?"',
    'false & echo "rc=$?"',
    'false & test -n "$!" && echo pid',
    'eval echo one two',
    'eval "echo hi; x=1"; echo $x',
    'x=5; eval "echo \$x"',
    'eval "for i in 1 2 3; do echo \$i; done"',
    'eval exit 3; echo after',
    '(echo a; echo b)',
    '(exit 3); echo $?',
    '(false); echo $?',
    'x=1; (x=2; echo "$x"); echo "$x"',
    'x=1; (unset x); echo "[$x]"',
    'p=$$; (test "$$" = "$p" && echo subshell-same)',
    'p=$$; echo "$(test "$$" = "$p" && echo cmdsub-same)"',
    'echo $(echo ")")',
    "echo $(echo ')(')",
    'echo $(echo \))',
    'echo $(echo "((")',
    'echo $(echo "hi #) there")',
    "echo $(echo 'it'\\''s')",
    'echo $(echo "\\")")',
    'echo $(echo $(echo ")"))',
    'echo "$(echo "$(echo ")")")"',
    'x=$(echo ")"); echo "$x"',
    'echo $(true)$(echo ")")',
    'echo $(echo `echo ")"`)',
    'echo $(echo ${a:-)})',
    "echo $(echo hi #comment )\n)",
    "echo $(echo x;#)\n)",
    "echo $(#c\necho hi)",
    'echo $(echo a#) b',
    'echo $(echo hi #)',
    'echo $(case x in x) echo y;; esac)',
    "echo $(case x in\nx) echo nl-in;; esac)",
    "echo $(case x in x) echo one;;\ny) echo two;; esac)",
    "echo $(case x in x\n) echo nlpat;; esac)",
    'echo $(case x in x) echo a;; *) echo b;; esac)',
    'echo $(case x in (x) echo q;; esac)',
    'echo $(case x in x|y) echo z;; esac)',
    'echo $(case x in x) echo "y)";; esac)',
    'echo $(case x in x) case y in y) echo z;; esac;; esac)',
    'echo $(case $(echo x) in x) echo dyn;; esac)',
    'echo $(case "x" in "x") echo q;; esac)',
    'echo $(case x in x) echo esac;; esac)',
    'echo $(case x in x) echo y; esac)',
    'echo $(case x in x) (echo sub);; esac)',
    'echo $(if true; then case x in x) echo y;; esac; fi)',
    "echo $(case x in\nx) echo ml;;\nesac)",
    'echo $(x=case; echo $x)',
    "trap 'echo parent-exit' EXIT; (trap); :",
    "(trap 'echo sub-exit' EXIT; :)",
    "trap '' INT; (trap)",
    '(if true; then echo yes; fi)',
    'printf "%s\n" hello',
    'printf "%s=%s\n" a 1 b 2',
    'printf "%s\n" a b c',
    'printf "[%5s][%-5s]\n" hi hi',
    'printf "%03d %d %x %X %o\n" 7 42 255 255 8',
    'printf "%c%c\n" abc xyz',
    'printf "a\tb\nc\n"',
    'printf "%d\n" abc; echo "rc=$?"',
    'printf "no newline"',
    'printf "%d-%s\n" 5',
    "cat <<EOF\nplain line one\nplain line two\nEOF",
    "cat <<-END\n\t\ttabbed body\n\tEND",
    "cat <<'Q'\nliteral $x and `cmd` stay\nQ",
    "wc -l <<EOF\na\nb\nc\nEOF",
    "v=42; cat <<EOF\nvalue is $v\nEOF",
    "cat <<EOF\nsub: $(echo deep)\nEOF",
    "cat <<EOF\ncs: $(echo \")\")\nEOF",
    "cat <<EOF\ncs: $(echo 'x)y')\nEOF",
    "cat <<EOF\narith: $((1+1))\nEOF",
    "x=1; cat <<EOF\nescaped \\$x literal\nEOF",
    'readonly x=1; echo "$x"',
    'readonly x=1; x=2; echo after',
    'readonly x=1; unset x; echo after',
    '(readonly x=1; x=2); echo after',
    '(echo ${X:?bad}); echo after',
    'exec echo replaced; echo after',
    'exec no-such-cmd-rush-xyz; echo after',
    'exec no-such-cmd-rush-xyz 2>&-; echo after',
    'x=hello; echo ${#x}',
    'echo ${#missing}',
    'f=foo.tar.gz; echo "${f#*.}|${f##*.}|${f%.*}|${f%%.*}"',
    'p=/usr/local/bin; echo "${p##*/} ${p%/*}"',
    'x=abc; echo "${x#xyz}|${x#*}|${x##*}"',
    'x=a1b; echo "${x#[[:alpha:]]}|${x##[[:alpha:]]*}|${x%[[:alpha:]]}"',
    'x=5abc; echo "${x#[![:alpha:]]}|${x%%[[:digit:]]*}"',
    'x=]tail; echo "${x#[[:digit:]\]]}"',
    'b=inner; echo ${a:-${b}}',
    'echo ${a:-${b:-x}}',
    'a=set; b=no; echo ${a:+${b:-yes}}',
    'b=B; echo "${a:-pre${b}post}"',
    'unset a; set -- ${a:-"x y"}; printf "<%s>\n" "$#:$1"',
    'unset a; set -- pre${a:-"x y"}post; printf "<%s>\n" "$#:$1"',
    'unset a; set -- ${a:-x" y "z}; printf "<%s>\n" "$#:$1"',
    'unset a; set -- ${a:-"*"}; printf "<%s>\n" "$#:$1"',
    'a=set; set -- ${a:+"x y"}; printf "<%s>\n" "$#:$1"',
    'unset a; set -- ${a:+"x y"}; printf "<%s>\n" "$#"',
    'unset a; set -- ${a:="x y"}; printf "<%s>\n" "$#:$1:$a"',
    'IFS=:; unset a; set -- ${a:-"x:y"}; printf "<%s>\n" "$#:$1"',
    'IFS=:; unset a; set -- ${a:-x:y}; printf "<%s>\n" "$#:$1:$2"',
    'unset a b; b="m n"; set -- ${a:-"$b"}; printf "<%s>\n" "$#:$1"',
    'unset a b; set -- ${a:-${b:-"m n"}}; printf "<%s>\n" "$#:$1"',
    'set -- "a b" c; unset x; set -- ${x:-"$@"}; printf "<%s>\n" "$#:$1:$2"',
    'set --; unset x; set -- ${x:-"$@"}; printf "<%s>\n" "$#:$1"',
    'set --; x=yes; set -- ${x:+"$@"}; printf "<%s>\n" "$#:$1"',
    'set --; unset x; set -- "${x:-$@}"; printf "<%s>\n" "$#:$1"',
    'set --; set -- "$@"; printf "<%s>\n" "$#"',
    'x=ab; echo ${x#*}}',
    'echo ${a:-{} ${a:-{x} ${a:-x{y}',
    'echo ${a:-"}"}',
    "echo ${a:-'}'}",
    'echo "${a:-"}"}"',
    "echo \"${a:-'}'}\"",
    "echo \"${a:-'x'}\"",
    'echo ${a:-$(echo })}',
    'echo ${a:-$(echo "})")}',
    'echo "${a:-$(echo "})")}"',
    'echo ${a:-$(echo ")")}',
    'echo ${a:-\}}',
    'echo "${a:-\}}"',
    'printf "%s\n" "${a:-\x}"',
    'x=a}b; echo ${x%\}b}',
    "echo ${a:-x'}'y}",
    "echo ${a:='}'}; echo $a",
    'echo ${#a}}',
    'echo "${a:-~}"',
    "b=B; cat <<EOF\n${a:-${b}}\nEOF",
    "cat <<EOF\n${a:-'}'}\nEOF",
    "cat <<EOF\n${a:-\"}\"}\nEOF",
    "cat <<EOF\n${a:-'x'}\nEOF",
    'set -u; x=ok; echo "$x"',
    'set -u; echo "${y:-fallback}"',
    'set -u; set a b; echo "$1$2"',
    'set -u; echo "$missing"; echo after',
    'set -u; echo "$1"; echo after',
    'set -e; false; echo after',
    'set -e; true; echo after',
    'set -e; if false; then echo no; fi; echo after',
    'set -e; false || true; echo after',
    'set -e; false && echo no; echo after',
    'set -e; true && false; echo after',
    'set -e; true && false && true; echo after',
    'set -e; ! false; echo after',
    'set -e; ! true; echo after',
    'set -e; ! { false; }; echo after',
    'set -e; if true; then false; fi; echo after',
    'set -e; if true; then false; fi || echo recovered; echo after',
    'set -e; f() { false; }; f; echo after',
    'set -e; if f() { false; }; f; then echo t; else echo no; fi',
    'set -e; for i in 1 2; do false; done; echo after',
    'set -e; while true; do false; done; echo after',
    'set -e; until false; do false; done; echo after',
    'set -e; case x in x) false;; esac; echo after',
    'set -e; case x in y) false;; esac; echo after',
    'set -e; eval false; echo after',
    'set -e; set +e; false; echo after',
    'set -e; ( false ); echo after',
    'set -e; ( false; echo no ); echo after',
    'set -e; if ( false; echo more ); then echo t; else echo f; fi',
    'set -e; if true; then ( false; echo more ); fi; echo after',
    'set -e; echo "X$(false; echo hi)Y"; echo done',
    'set -e; (exit 7); echo after',
    'unset IFS; x=a:b; set -- ${IFS:=:}$x; printf "<%s>" "$@"; echo ":$#"',
    'unset IFS; set -- "" a "" b ""; set -- $@; printf "<%s>" "$@"; echo ":$#"',
    'IFS=:; set -- "" a "" b ""; set -- $@; printf "<%s>" "$@"; echo ":$#"',
    'IFS=": "; set -- "" a "" b ""; set -- $@; printf "<%s>" "$@"; echo ":$#"',
    'IFS=" :"; set -- "" a "" b ""; set -- $@; printf "<%s>" "$@"; echo ":$#"',
    'x="\\q"; set -- $x; printf "<%s>" "$@"',
    'set -- $(printf "\\\\q"); printf "<%s>" "$@"',
    'IFS=2; set -- $((12 + 11)); printf "<%s>" "$@"; echo ":$#"',
    'touch rush-at-xa rush-at-xb; set -- "rush-at-x*" ""; set -- $@; printf "<%s>" "$@"; echo ":$#"; ' \
    'rm -f rush-at-xa rush-at-xb',
    'touch rush-at-xa; set -- "rush-at-x*"; set -- "$@"; printf "<%s>" "$@"; rm -f rush-at-xa',
    'IFS=:; v="a::b"; set -- $v; echo $#',
    'IFS=:; v=":a:b:"; set -- $v; printf "<%s>" "$@"; echo',
    'IFS=:; v="a:"; set -- $v; echo $#',
    'IFS=:; v="a::"; set -- $v; echo $#',
    'IFS=:; v="::"; set -- $v; echo $#',
    'IFS=:; v=":"; set -- $v; echo $#',
    'IFS=:; v=""; set -- $v; echo $#',
    'IFS=" :"; v="a  :  b"; set -- $v; printf "<%s>" "$@"; echo',
    'IFS=" :"; v=":x:"; set -- $v; printf "<%s>" "$@"; echo',
    'IFS=" :"; v="  a  "; set -- $v; printf "<%s>" "$@"; echo',
    'a="x:"; b=":y"; IFS=:; set -- $a$b; echo $#',
    'a="x"; b="y"; IFS=:; set -- $a$b; echo "$#:$1"',
    'IFS=" "; v="  hi   there  "; set -- $v; echo $#',
    'IFS=":"; v="a:b"; set -- p$v"q"; printf "<%s>" "$@"; echo',
    'IFS=" "; v="  x  "; set -- "pre"$v; printf "<%s>" "$@"; echo',
    'IFS=; set -- a b c; printf "[%s]" "$*"; echo',
    'unset IFS; set -- a b c; printf "[%s]" "$*"; echo',
    'IFS=-; set -- a b c; printf "[%s]" "$*"; echo',
    'IFS=:; set -- "a b" c; set -- $*; echo $#',
    'IFS=""; set -- a b c; set -- $*; echo $#',
    'IFS=" "; set -- "p q" r; set -- $*; echo $#',
    'IFS=:; set -- a b c; X=$*; echo "[$X]"',
    'echo $((2+3*4))',
    'echo $(((2+3)*4))',
    'echo $((17/5)) $((17%5)) $((-17/5)) $((-17%5))',
    'echo $((7 % -3)) $((-7 % 3))',
    'echo $((1<<4)) $((256>>2)) $((5&3)) $((5|2)) $((5^1)) $((~0))',
    'echo $((3<5)) $((5>3)) $((3<=3)) $((4>=9)) $((3==3)) $((3!=3))',
    'echo $((2&&0)) $((0||3)) $((!0)) $((!5))',
    'echo $((1?22:33)) $((0?22:33)) $(( 1 ? 2 : 3 ? 4 : 5 ))',
    'echo $((010)) $((0x1F)) $((0XfF))',
    'x=5; echo $((x+1)) $(($x+1))',
    'echo $((nosuch+1))',
    'x=5; echo $(( x > 3 ? x*2 : 0 ))',
    'echo $((9223372036854775807+1))',
    'echo $((0 && 1/0)) $((1 || 1/0))',
    'echo $(( $(echo 3) + 4 ))',
    'echo $((- -5)) $((+ +5)) $((!!5)) $(( ~ ~ 0 )) $((2 + -3))',
    'x=010; echo $((x))',
    'i=0; i=$((i+1)); i=$((i+1)); echo $i',
    'echo a; echo $((1/0)); echo b',
    'x=abc; echo $((x+1))',
    'echo $((1+))',
    'echo $((2**10))',
    'echo $((x=5)); echo "$x"',
    'x=10; echo $((x+=2)) $((x-=3)) $((x*=2)) $((x/=4)) $((x%=4)); echo $x',
    'x=1; echo $((x<<=4)) $((x>>=1)) $((x|=1)) $((x&=2)) $((x^=7))',
    'echo $((a=b=3)); echo "$a $b"',
    'echo $((y = 1 ? 2 : 3)); echo $y',
    'x=5; echo $(( x>0 ? (x=100) : 0 )); echo $x',
    'a=3; echo $((a += a += 1)); echo $a',
    'i=0; while [ $i -lt 3 ]; do i=$((i+1)); done; echo $i',
    'echo $((5=3))',
    'echo $((x=))',
    'echo ~',
    'echo ~/foo',
    'echo a~ ~~ x~/y',
    'echo "~" "~/a"',
    'echo ~root ~root/bin',
    'echo ~nosuchuser_zzz',
    'P=~/a:~root:b; echo "$P"',
    'echo ${u:-~}',
    'echo $((~5)) $((~0))',
    'x=g; f() { local x=in; echo $x; }; f; echo $x',
    'f() { local a b; a=1; b=2; echo "$a-$b"; }; f; echo "[$a][$b]"',
    'x=1; f() { local x=2; g; }; g() { echo $x; }; f',
    'n=5; f() { local n=$((n+1)); echo $n; }; f; echo $n',
    'x=keep; f() { local x; echo "[$x]"; }; f; echo $x',
    'set -o errexit; false; echo after',
    'set -o errexit; if true; then echo c; false; fi || echo rec; echo done',
    'set +o errexit; false; echo after',
    'set -o nounset; echo "${x:-ok}"; echo $undef; echo no',
    'set -a; X=ok; printenv X',
    'set -a; X=ok; set +a; Y=no; printenv X; printenv Y; echo "rc=$?"',
    'type echo set if',
    'type ls',
    'f() { :; }; type f',
    'type nosuchcmd_zzz',
    'command -v echo',
    'command -v ls',
    'f() { :; }; command -v f',
    'command -v nosuchcmd_zzz; echo "rc=$?"',
    'command -v; echo "rc=$?"',
    'command -p true; echo "rc=$?"',
    'command -p echo hi',
    'command -p cd /tmp; pwd',
    'command -p nosuchcmd_zzz; echo "rc=$?"',
    'command -pv nosuchcmd_zzz; echo "rc=$?"',
    'command -p -v true',
    'f() { :; }; command -p -v f',
    'f() { echo function; }; command -pv f; command f; echo "rc=$?"',
    'command -p -- echo hi',
    'PATH=/nonexistent; command -p ls /usr/bin/dash; echo "rc=$?"',
    'PATH=/nonexistent; command ls; echo "rc=$?"',
    'command - echo hi; echo "rc=$?"',
    'command +v ls; echo "rc=$?"',
    'command -z echo; echo "rc=$?"',
    'X=old; X=new :; echo "X=$X"',
    'unset X; X=new :; printenv X; echo "X=$X rc=$?"',
    'X=old; export X; X=new :; printenv X',
    'X=old; X=new command :; echo "X=$X"',
    'X=outer; f() { echo "in=$X"; X=body; Y=live; }; X=temp f; echo "out=$X:$Y"',
    'unset X; f() { printenv X; }; X=temp f; echo "after=${X-unset}"; printenv X; echo "rc=$?"',
    'unset X; f() { export X=body; }; X=temp f; echo "after=${X-unset}"; printenv X; echo "rc=$?"',
    'readonly X=locked; X=new /bin/true; echo not-reached',
    'readonly X=locked; OPEN=yes X=new /bin/true; echo not-reached',
    'X=prefix export Y=value; echo "X=$X Y=$Y"; printenv X; echo "rc=$?"',
    'X=prefix unset X; echo "X=${X-unset}"',
    "trap 'echo trap=$X' EXIT; X=persist shift 5",
    "X=child exec sh -c 'echo X=$X'",
    'command shift 5; echo "after=$?"',
    'command . /no/such/rush-command; echo "after=$?"',
    'command eval "bad ("; echo "after=$?"',
    "command eval 'echo ${MISSING?bad}'; echo \"after=$?\"",
    'readonly X=fixed; command export X=changed; echo "after=$? X=$X"',
    'command exit bad; echo "after=$?"',
    'X=outer; X=inner command printenv X; echo "parent=$X"',
    'X=outer; X=inner command command printenv X; echo "parent=$X"',
    "X=outer; X=inner command -p sh -c 'echo child=$X'; echo \"parent=$X\"",
    "X=outer; X=inner command eval 'echo seen=$X; X=changed; Y=yes'; echo \"X=$X Y=$Y\"",
    'HOME=/tmp command cd; pwd; echo "HOME=$HOME"',
    "IFS=: command read a b <<EOF\nx:y\nEOF\necho \"$a/$b\"",
    'echo() { echo no; }; command echo hi',
    'cd() { echo CDFUNC; }; cd /tmp; echo after',
    'cd /tmp; cd -; pwd',
    'd=$(pwd); cd /tmp; test "$OLDPWD" = "$d" && test "$PWD" = /tmp && echo pwd-ok',
    'd=rush-cdpath-diff; rm -rf /tmp/$d; mkdir -p /tmp/$d; CDPATH=/tmp; cd $d; pwd; cd /; rmdir /tmp/$d',
    'true() { echo TF; }; true; echo "rc=$?"',
    'greet() { echo "hi $1"; }; greet world',
    'command -V echo',
    'command -V set',
    'command -V if',
    'command -V nosuch_zz; echo "rc=$?"',
    'command -V; echo "rc=$?"',
    'command -pV echo',
    'command -v -V echo; command -V -v echo'
  ].freeze
end

RSpec.shared_examples 'a differential language corpus shard' do |shard:, total:|
  before { skip 'dash not installed' unless system('command -v dash > /dev/null 2>&1') }

  DifferentialLanguageCorpus::CASES.each.with_index(1) do |snippet, index|
    next unless ((index - 1) % total) == shard

    id = format('language-%03d', index)
    it "#{id}: matches dash for: #{snippet}" do
      expect(rush(snippet)).to eq(dash(snippet))
    end
  end
end
